/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class AboutUs extends javax.swing.JFrame {

    /**
     * Creates new form AboutUs
     */
    public AboutUs() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblAboutUs = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        imgDoctoraDiagnostico = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        imgDecoracion = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        imgEspecialistas = new javax.swing.JLabel();
        lblAgenda = new javax.swing.JLabel();
        imgHistorial = new javax.swing.JLabel();
        lblDescripcionHistorial = new javax.swing.JLabel();
        lblDescripcionEspecialistas = new javax.swing.JLabel();
        lblDescripcionAgenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setPreferredSize(new java.awt.Dimension(1327, 705));
        FondoPrincipal.setLayout(null);

        lblHome.setBackground(new java.awt.Color(255, 255, 255));
        lblHome.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblHome.setText("HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblHome);
        lblHome.setBounds(390, 40, 140, 48);

        lblAboutUs.setBackground(new java.awt.Color(255, 255, 255));
        lblAboutUs.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblAboutUs.setText("ABOUT US");
        lblAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutUsMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblAboutUs);
        lblAboutUs.setBounds(585, 40, 200, 48);

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Logos/Logo_Descripcion.png"))); // NOI18N
        FondoPrincipal.add(imgLogo);
        imgLogo.setBounds(0, 0, 380, 110);

        lblLogin.setBackground(new java.awt.Color(255, 255, 255));
        lblLogin.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblLogin.setText("LOGIN");
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblLogin);
        lblLogin.setBounds(1130, 40, 150, 48);

        imgDoctoraDiagnostico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Personas/DoctoraDiagnostico.png"))); // NOI18N
        FondoPrincipal.add(imgDoctoraDiagnostico);
        imgDoctoraDiagnostico.setBounds(880, 30, 430, 410);

        lblTitulo2.setFont(new java.awt.Font("Palatino Linotype", 1, 42)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(0, 0, 153));
        lblTitulo2.setText("Nuestra Oferta");
        FondoPrincipal.add(lblTitulo2);
        lblTitulo2.setBounds(530, 400, 300, 60);

        lblContact.setBackground(new java.awt.Color(255, 255, 255));
        lblContact.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblContact.setText("CONTACT");
        lblContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContactMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblContact);
        lblContact.setBounds(840, 40, 200, 48);

        imgDecoracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Decoraciones/DecoracionMenu2.png"))); // NOI18N
        FondoPrincipal.add(imgDecoracion);
        imgDecoracion.setBounds(-290, -360, 1630, 690);

        lblDescripcion.setFont(new java.awt.Font("Arial Narrow", 0, 28)); // NOI18N
        lblDescripcion.setText("<html>Gestiona tus citas médicas de forma rápida y segura. <p>Olvídate de las largas esperas y conéctate con los mejores<p>profesionales.</html>\n");
        FondoPrincipal.add(lblDescripcion);
        lblDescripcion.setBounds(20, 230, 600, 160);

        lblTitulo1.setFont(new java.awt.Font("Palatino Linotype", 1, 52)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(0, 0, 153));
        lblTitulo1.setText("Cuidamos de ti, siempre");
        FondoPrincipal.add(lblTitulo1);
        lblTitulo1.setBounds(20, 190, 590, 90);

        imgEspecialistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Personas/Especialistas.jpg"))); // NOI18N
        imgEspecialistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgEspecialistasMouseClicked(evt);
            }
        });
        FondoPrincipal.add(imgEspecialistas);
        imgEspecialistas.setBounds(130, 460, 140, 150);

        lblAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/Agenda.jpg"))); // NOI18N
        lblAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgendaMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblAgenda);
        lblAgenda.setBounds(610, 460, 140, 150);

        imgHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/Historial.jpg"))); // NOI18N
        imgHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHistorialMouseClicked(evt);
            }
        });
        FondoPrincipal.add(imgHistorial);
        imgHistorial.setBounds(1100, 450, 140, 160);

        lblDescripcionHistorial.setFont(new java.awt.Font("Arial Narrow", 3, 25)); // NOI18N
        lblDescripcionHistorial.setText("<html><center>Accede a<p>tu historial</center></html>");
        FondoPrincipal.add(lblDescripcionHistorial);
        lblDescripcionHistorial.setBounds(1110, 610, 110, 50);

        lblDescripcionEspecialistas.setFont(new java.awt.Font("Arial Narrow", 3, 25)); // NOI18N
        lblDescripcionEspecialistas.setText("<html><center>Encuentra<p>Especialistas</center></html>");
        FondoPrincipal.add(lblDescripcionEspecialistas);
        lblDescripcionEspecialistas.setBounds(130, 610, 130, 60);

        lblDescripcionAgenda.setFont(new java.awt.Font("Arial Narrow", 3, 25)); // NOI18N
        lblDescripcionAgenda.setText("<html><center>Agenda fácil<p>y rápido</center></html>");
        FondoPrincipal.add(lblDescripcionAgenda);
        lblDescripcionAgenda.setBounds(620, 610, 130, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );

        FondoPrincipal.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        // TODO add your handling code here:
        MenuPrincipal form=new MenuPrincipal();
        form.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutUsMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null , "Ya estas en About us");
    }//GEN-LAST:event_lblAboutUsMouseClicked

    private void lblContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContactMouseClicked
        // TODO add your handling code here:
        Contact form = new Contact();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblContactMouseClicked

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        // TODO add your handling code here:
        IniciarSesion form = new IniciarSesion();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblLoginMouseClicked

    private void imgEspecialistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgEspecialistasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_imgEspecialistasMouseClicked

    private void lblAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAgendaMouseClicked

    private void imgHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHistorialMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_imgHistorialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JLabel imgDecoracion;
    private javax.swing.JLabel imgDoctoraDiagnostico;
    private javax.swing.JLabel imgEspecialistas;
    private javax.swing.JLabel imgHistorial;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblAboutUs;
    private javax.swing.JLabel lblAgenda;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcionAgenda;
    private javax.swing.JLabel lblDescripcionEspecialistas;
    private javax.swing.JLabel lblDescripcionHistorial;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    // End of variables declaration//GEN-END:variables
}
