/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAcciones;
import Modelo.FactoryEnvioWhatsApp;
import Modelo.FactoryManejadorContacto;
import Modelo.ManejadorContacto;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class Contact extends javax.swing.JFrame {
    
    private ControladorAcciones controlador;

    /**
     * Creates new form Contact
     */
    public Contact() {
        initComponents();
        this.setLocationRelativeTo(null);
        controlador = new ControladorAcciones();
    }
    
   
    
   
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblAboutUs = new javax.swing.JLabel();
        imgDecoracionMenu = new javax.swing.JLabel();
        imgContacto = new javax.swing.JLabel();
        imgUbicacion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        imgWasap = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblContacto = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Enviar = new javax.swing.JButton();
        imgFondoWhatsap = new javax.swing.JLabel();
        imgFondoCorreo = new javax.swing.JLabel();
        imgFondoUbicacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblHome.setBackground(new java.awt.Color(255, 255, 255));
        lblHome.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblHome.setText("HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblHome);
        lblHome.setBounds(410, 50, 120, 48);

        lblTitulo1.setFont(new java.awt.Font("Palatino Linotype", 1, 65)); // NOI18N
        lblTitulo1.setText("CONTACTO");
        FondoPrincipal.add(lblTitulo1);
        lblTitulo1.setBounds(470, 220, 400, 90);

        lblContact.setBackground(new java.awt.Color(255, 255, 255));
        lblContact.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblContact.setText("CONTACT");
        lblContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContactMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblContact);
        lblContact.setBounds(890, 50, 200, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Logos/Logo_Descripcion.png"))); // NOI18N
        FondoPrincipal.add(jLabel1);
        jLabel1.setBounds(0, 0, 310, 100);

        lblLogin.setBackground(new java.awt.Color(255, 255, 255));
        lblLogin.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblLogin.setText("LOGIN");
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblLogin);
        lblLogin.setBounds(1160, 50, 130, 48);

        lblAboutUs.setBackground(new java.awt.Color(255, 255, 255));
        lblAboutUs.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblAboutUs.setText("ABOUT US");
        lblAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutUsMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblAboutUs);
        lblAboutUs.setBounds(620, 50, 200, 48);

        imgDecoracionMenu.setBackground(new java.awt.Color(245, 249, 252));
        imgDecoracionMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Decoraciones/DecoracionMenu4.png"))); // NOI18N
        FondoPrincipal.add(imgDecoracionMenu);
        imgDecoracionMenu.setBounds(0, 0, 1327, 286);

        imgContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/Correo.jpg"))); // NOI18N
        FondoPrincipal.add(imgContacto);
        imgContacto.setBounds(870, 450, 60, 50);

        imgUbicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/Ubicacion.png"))); // NOI18N
        FondoPrincipal.add(imgUbicacion);
        imgUbicacion.setBounds(880, 580, 60, 60);

        txtNombre.setBackground(new java.awt.Color(220, 233, 255));
        txtNombre.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtNombre.setText("Nombre");
        FondoPrincipal.add(txtNombre);
        txtNombre.setBounds(100, 410, 180, 30);

        imgWasap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/Contacto.png"))); // NOI18N
        imgWasap.setText("jLabel2");
        FondoPrincipal.add(imgWasap);
        imgWasap.setBounds(870, 330, 60, 50);

        txtCorreo.setBackground(new java.awt.Color(220, 233, 255));
        txtCorreo.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtCorreo.setText("Correo");
        FondoPrincipal.add(txtCorreo);
        txtCorreo.setBounds(100, 340, 180, 30);

        lblCorreo.setFont(new java.awt.Font("Palatino Linotype", 1, 28)); // NOI18N
        lblCorreo.setText("lasmed@medisalud.com");
        FondoPrincipal.add(lblCorreo);
        lblCorreo.setBounds(940, 460, 305, 60);

        lblContacto.setFont(new java.awt.Font("Palatino Linotype", 1, 28)); // NOI18N
        lblContacto.setText("(+57) 312 435 2786");
        FondoPrincipal.add(lblContacto);
        lblContacto.setBounds(940, 350, 230, 40);

        lblUbicacion.setFont(new java.awt.Font("Palatino Linotype", 1, 28)); // NOI18N
        lblUbicacion.setText("Villavicencio , Meta");
        FondoPrincipal.add(lblUbicacion);
        lblUbicacion.setBounds(950, 590, 260, 40);

        txtCelular.setBackground(new java.awt.Color(220, 233, 255));
        txtCelular.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtCelular.setText("Celular");
        FondoPrincipal.add(txtCelular);
        txtCelular.setBounds(410, 340, 170, 30);

        jTextPane1.setBackground(new java.awt.Color(220, 233, 255));
        jScrollPane1.setViewportView(jTextPane1);

        FondoPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(100, 470, 560, 120);

        Enviar.setBackground(new java.awt.Color(220, 233, 255));
        Enviar.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        Enviar.setText("Enviar");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });
        FondoPrincipal.add(Enviar);
        Enviar.setBounds(100, 630, 110, 34);

        imgFondoWhatsap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/FondoWasap.png"))); // NOI18N
        imgFondoWhatsap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgFondoWhatsapMouseClicked(evt);
            }
        });
        FondoPrincipal.add(imgFondoWhatsap);
        imgFondoWhatsap.setBounds(850, 300, 410, 120);

        imgFondoCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/FondoCorreo.png"))); // NOI18N
        imgFondoCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgFondoCorreoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(imgFondoCorreo);
        imgFondoCorreo.setBounds(850, 430, 400, 100);

        imgFondoUbicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/FondoUbicacion.png"))); // NOI18N
        imgFondoUbicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgFondoUbicacionMouseClicked(evt);
            }
        });
        FondoPrincipal.add(imgFondoUbicacion);
        imgFondoUbicacion.setBounds(850, 550, 410, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1327, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        // TODO add your handling code here:
        MenuPrincipal form=new MenuPrincipal();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutUsMouseClicked
        // TODO add your handling code here:
        AboutUs form=new AboutUs();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAboutUsMouseClicked

    private void lblContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContactMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null , "Ya estas en Contact");
    }//GEN-LAST:event_lblContactMouseClicked

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        // TODO add your handling code here:
        IniciarSesion form = new IniciarSesion();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblLoginMouseClicked

    private void imgFondoWhatsapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgFondoWhatsapMouseClicked
        // TODO add your handling code here:
        controlador.enviarWhatsApp("573124352786");

        
    }//GEN-LAST:event_imgFondoWhatsapMouseClicked

    private void imgFondoCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgFondoCorreoMouseClicked
        // TODO add your handling code here:
         controlador.enviarCorreo("martindavidvb@gmail.com", "Asunto", "Hola, este es un mensaje.");
            
    }//GEN-LAST:event_imgFondoCorreoMouseClicked

    private void imgFondoUbicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgFondoUbicacionMouseClicked
        // TODO add your handling code here:
         controlador.abrirUbicacion("Calle 15 #40-01, Villavicencio, Meta");
    }//GEN-LAST:event_imgFondoUbicacionMouseClicked

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:// Obtener datos del formulario
        String nombre = txtNombre.getText();
        String correo = txtCorreo.getText();
        String celular = txtCelular.getText();
        String mensaje = jTextPane1.getText();
        
        System.out.println("Nombre: " + nombre);
        System.out.println("Correo: " + correo);
        System.out.println("Celular: " + celular);
        System.out.println("Mensaje: " + mensaje);


        // Crear factory y manejador
        FactoryManejadorContacto factory = new FactoryEnvioWhatsApp();
        ManejadorContacto manejador = factory.crearManejador();

        // Procesar el contacto, abrir WhatsApp
        manejador.procesarContacto(nombre, correo, celular, mensaje);

    }//GEN-LAST:event_EnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JLabel imgContacto;
    private javax.swing.JLabel imgDecoracionMenu;
    private javax.swing.JLabel imgFondoCorreo;
    private javax.swing.JLabel imgFondoUbicacion;
    private javax.swing.JLabel imgFondoWhatsap;
    private javax.swing.JLabel imgUbicacion;
    private javax.swing.JLabel imgWasap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblAboutUs;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
