/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAcciones;
import Modelo.Paciente;
import Controlador.PacienteDAO;
import Modelo.Sesion;
import Modelo.SesionAdmin;
import Modelo.SesionDoctor;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class IniciarSesion extends javax.swing.JFrame {
    
   

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        SesionAdmin.getNombreAdmin();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        FondoColor = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        lbIVolver = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        lblRegistro = new javax.swing.JLabel();
        lblInicioSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        FondoColor.setBackground(new java.awt.Color(220, 233, 255));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Logos/Logo_Descripcion.png"))); // NOI18N

        lbIVolver.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        lbIVolver.setText("Volver");
        lbIVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FondoColorLayout = new javax.swing.GroupLayout(FondoColor);
        FondoColor.setLayout(FondoColorLayout);
        FondoColorLayout.setHorizontalGroup(
            FondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoColorLayout.createSequentialGroup()
                .addGroup(FondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoColorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbIVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoColorLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        FondoColorLayout.setVerticalGroup(
            FondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoColorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbIVolver)
                .addGap(145, 145, 145)
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCorreo.setBackground(new java.awt.Color(220, 233, 255));
        txtCorreo.setFont(new java.awt.Font("Sylfaen", 1, 25)); // NOI18N
        txtCorreo.setText("Correo");

        txtContrasena.setBackground(new java.awt.Color(220, 233, 255));
        txtContrasena.setFont(new java.awt.Font("Sylfaen", 1, 25)); // NOI18N
        txtContrasena.setText("Contraseña");
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });

        btnIniciarSesion.setBackground(new java.awt.Color(173, 220, 255));
        btnIniciarSesion.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        btnIniciarSesion.setText("Entrar");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        lblRegistro.setFont(new java.awt.Font("Sylfaen", 1, 35)); // NOI18N
        lblRegistro.setText("Registro");
        lblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistroMouseClicked(evt);
            }
        });

        lblInicioSesion.setFont(new java.awt.Font("Sylfaen", 1, 35)); // NOI18N
        lblInicioSesion.setText("Inicio Sesión");
        lblInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInicioSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FondoPrincipalLayout = new javax.swing.GroupLayout(FondoPrincipal);
        FondoPrincipal.setLayout(FondoPrincipalLayout);
        FondoPrincipalLayout.setHorizontalGroup(
            FondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoPrincipalLayout.createSequentialGroup()
                .addComponent(FondoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(FondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoPrincipalLayout.createSequentialGroup()
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FondoPrincipalLayout.createSequentialGroup()
                        .addComponent(lblInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(FondoPrincipalLayout.createSequentialGroup()
                        .addGroup(FondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        FondoPrincipalLayout.setVerticalGroup(
            FondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoPrincipalLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(FondoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistro)
                    .addComponent(lblInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnIniciarSesion)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
    
    String correo = txtCorreo.getText();
    String contrasena = txtContrasena.getText();

    ControladorAcciones controlador = new ControladorAcciones();
    String tipoUsuario = controlador.obtenerTipoUsuario(correo, contrasena);

    if ("doctor".equals(tipoUsuario)) {
        String nombreDoctor = controlador.obtenerNombreDoctor(correo); 
        String apellidoDoctor = controlador.obtenerApellidoDoctor(correo);
        SesionDoctor.setNombreDoctor(nombreDoctor);
        SesionDoctor.setApellidoDoctor(apellidoDoctor);

        Menu_Doctor menu = new Menu_Doctor();
        menu.setVisible(true);
        this.dispose();

    } else if ("paciente".equals(tipoUsuario)) {
        Paciente paciente = PacienteDAO.validarYObtenerPaciente(correo, contrasena);
        if (paciente != null) {
            Sesion.setPaciente(paciente); // Guarda el paciente en sesión
            Menu_Paciente menu = new Menu_Paciente();
            menu.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos del paciente.");
        }

    } else if ("admin".equals(tipoUsuario)) {
        String nombreAdmin = controlador.obtenerNombreAdmin(correo); 
        SesionAdmin.setNombreAdmin(nombreAdmin); // Guarda el nombre en sesión

        Menu_Admin menu = new Menu_Admin(); // Asegúrate de tener esta clase creada
        menu.setVisible(true);
        this.dispose();

    } else {
        JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.");
    }

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void lblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseClicked
        // TODO add your handling code here:
        Registro form = new Registro();
        form.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_lblRegistroMouseClicked

    private void lbIVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIVolverMouseClicked
        // TODO add your handling code here:
        MenuPrincipal form=new MenuPrincipal();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbIVolverMouseClicked

    private void lblInicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioSesionMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ya estas iniciando Sesión");
    }//GEN-LAST:event_lblInicioSesionMouseClicked

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoColor;
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lbIVolver;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
