/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author marti
 */
public class Menu_Doctor_Historia_Clinica_Registrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu_Doctor_Historia_Clinica_Registrar
     */
    public Menu_Doctor_Historia_Clinica_Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTituloFecha = new javax.swing.JLabel();
        lblTituloPaciente = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cbPaciente = new javax.swing.JComboBox<>();
        lblTituloMotivoConsulta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMotivoConsulta = new javax.swing.JTextArea();
        lblTituloMotivoConsulta1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaAntecedentes = new javax.swing.JTextArea();
        lblTituloMotivoConsulta2 = new javax.swing.JLabel();
        cbEspecialidad = new javax.swing.JComboBox<>();
        lblTituloDiagnostico = new javax.swing.JLabel();
        cbDiagnostico = new javax.swing.JComboBox<>();
        lblTituloPlanTratamientos = new javax.swing.JLabel();
        lblTituloMedicamentos = new javax.swing.JLabel();
        lblTituloDosis = new javax.swing.JLabel();
        lblTituloDesde = new javax.swing.JLabel();
        txtMedicamentos = new javax.swing.JTextField();
        txtDosis = new javax.swing.JTextField();
        lblTituloHasta = new javax.swing.JLabel();
        dtDesde = new com.toedter.calendar.JDateChooser();
        dtHasta = new com.toedter.calendar.JDateChooser();

        setTitle("Registro Historia Clinica");

        lblTitulo.setFont(new java.awt.Font("Sylfaen", 1, 38)); // NOI18N
        lblTitulo.setText("Registro Historia Clinica");

        lblTituloFecha.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloFecha.setText("Fecha : ");

        lblTituloPaciente.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloPaciente.setText("Paciente : ");

        cbPaciente.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cbPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        lblTituloMotivoConsulta.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloMotivoConsulta.setText("Especialidad :");

        txaMotivoConsulta.setColumns(20);
        txaMotivoConsulta.setRows(5);
        jScrollPane1.setViewportView(txaMotivoConsulta);

        lblTituloMotivoConsulta1.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloMotivoConsulta1.setText("Motivo de Consulta :");

        txaAntecedentes.setColumns(20);
        txaAntecedentes.setRows(5);
        jScrollPane2.setViewportView(txaAntecedentes);

        lblTituloMotivoConsulta2.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloMotivoConsulta2.setText("Antecedentes :");

        cbEspecialidad.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Medicina General", "Cardiología", "Neurología", "Ginecología", "Obstetricia", "Pediatría", "Oftalmología", "Odontología" }));

        lblTituloDiagnostico.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloDiagnostico.setText("Diagnostico :");

        cbDiagnostico.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cbDiagnostico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", " " }));
        cbDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiagnosticoActionPerformed(evt);
            }
        });

        lblTituloPlanTratamientos.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloPlanTratamientos.setText("Plan de Tratamientos");

        lblTituloMedicamentos.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloMedicamentos.setText("Medicamentos :");

        lblTituloDosis.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloDosis.setText("Dosis :");

        lblTituloDesde.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloDesde.setText("Desde :");

        lblTituloHasta.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloHasta.setText("Hasta :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTituloFecha)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTituloMotivoConsulta2)
                        .addComponent(jScrollPane2)
                        .addComponent(lblTituloMotivoConsulta)
                        .addComponent(lblTituloMotivoConsulta1)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTituloPaciente)
                            .addGap(18, 18, 18)
                            .addComponent(cbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTituloDiagnostico)
                            .addGap(18, 18, 18)
                            .addComponent(cbDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTituloMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMedicamentos))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(lblTituloPlanTratamientos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTituloDesde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTituloDosis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTituloHasta, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloFecha)
                    .addComponent(lblTituloPaciente)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloMotivoConsulta1)
                    .addComponent(lblTituloDiagnostico)
                    .addComponent(cbDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblTituloMotivoConsulta2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblTituloPlanTratamientos)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloMedicamentos)
                            .addComponent(txtMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloDosis)
                            .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTituloMotivoConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloDesde)
                            .addComponent(dtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloHasta)
                            .addComponent(dtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDiagnosticoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDiagnostico;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JComboBox<String> cbPaciente;
    private com.toedter.calendar.JDateChooser dtDesde;
    private com.toedter.calendar.JDateChooser dtHasta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloDesde;
    private javax.swing.JLabel lblTituloDiagnostico;
    private javax.swing.JLabel lblTituloDosis;
    private javax.swing.JLabel lblTituloFecha;
    private javax.swing.JLabel lblTituloHasta;
    private javax.swing.JLabel lblTituloMedicamentos;
    private javax.swing.JLabel lblTituloMotivoConsulta;
    private javax.swing.JLabel lblTituloMotivoConsulta1;
    private javax.swing.JLabel lblTituloMotivoConsulta2;
    private javax.swing.JLabel lblTituloPaciente;
    private javax.swing.JLabel lblTituloPlanTratamientos;
    private javax.swing.JTextArea txaAntecedentes;
    private javax.swing.JTextArea txaMotivoConsulta;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtMedicamentos;
    // End of variables declaration//GEN-END:variables
}
