/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author marti
 */
public class Menu_Doctor_Historia_Clinica_VerHistoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu_Doctor_Historia_Clinica_Crear
     */
    public Menu_Doctor_Historia_Clinica_VerHistoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloAntecedentes = new javax.swing.JLabel();
        lblMotivoConsulta = new javax.swing.JLabel();
        lblAntecedentes = new javax.swing.JLabel();
        lblDiagnostico = new javax.swing.JLabel();
        lblTituloPlanTratamientos = new javax.swing.JLabel();
        lblTituloPaciente = new javax.swing.JLabel();
        lblTituloNoDocumento = new javax.swing.JLabel();
        lblTituloMedicamentos = new javax.swing.JLabel();
        lblTituloEspecialidad = new javax.swing.JLabel();
        lblTituloNombre = new javax.swing.JLabel();
        lblTituloHasta = new javax.swing.JLabel();
        lblTituloFechaMedicamentos = new javax.swing.JLabel();
        lblNoDocumento = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        lblFechaMedicamentos = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        lblPlanTratamientos = new javax.swing.JLabel();
        lblMedicamentos = new javax.swing.JLabel();
        lblTituloFecha = new javax.swing.JLabel();
        lblHasta = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTituloMotivoConsulta = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTituloDiagnostico = new javax.swing.JLabel();

        setTitle("Ver Historia Clinica");
        setPreferredSize(new java.awt.Dimension(755, 379));

        jPanel1.setLayout(null);

        lblTituloAntecedentes.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloAntecedentes.setText("Antecedentes :");
        jPanel1.add(lblTituloAntecedentes);
        lblTituloAntecedentes.setBounds(90, 250, 133, 27);

        lblMotivoConsulta.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblMotivoConsulta.setText("xxxxx");
        jPanel1.add(lblMotivoConsulta);
        lblMotivoConsulta.setBounds(210, 190, 170, 27);

        lblAntecedentes.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblAntecedentes.setText("xxxxx");
        jPanel1.add(lblAntecedentes);
        lblAntecedentes.setBounds(230, 250, 150, 27);

        lblDiagnostico.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblDiagnostico.setText("xxxxx");
        jPanel1.add(lblDiagnostico);
        lblDiagnostico.setBounds(220, 130, 170, 27);

        lblTituloPlanTratamientos.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloPlanTratamientos.setText("Plan de Tratamientos :");
        jPanel1.add(lblTituloPlanTratamientos);
        lblTituloPlanTratamientos.setBounds(400, 210, 208, 27);

        lblTituloPaciente.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloPaciente.setText("Paciente : ");
        jPanel1.add(lblTituloPaciente);
        lblTituloPaciente.setBounds(400, 90, 95, 27);

        lblTituloNoDocumento.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloNoDocumento.setText("No. Documento :");
        jPanel1.add(lblTituloNoDocumento);
        lblTituloNoDocumento.setBounds(400, 130, 154, 27);

        lblTituloMedicamentos.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblTituloMedicamentos.setText("Medicamentos :");
        jPanel1.add(lblTituloMedicamentos);
        lblTituloMedicamentos.setBounds(400, 250, 140, 25);

        lblTituloEspecialidad.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloEspecialidad.setText("Especialidad :");
        jPanel1.add(lblTituloEspecialidad);
        lblTituloEspecialidad.setBounds(400, 170, 126, 27);

        lblTituloNombre.setFont(new java.awt.Font("Sylfaen", 1, 38)); // NOI18N
        lblTituloNombre.setText("Nombre");
        jPanel1.add(lblTituloNombre);
        lblTituloNombre.setBounds(440, 30, 160, 50);

        lblTituloHasta.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblTituloHasta.setText("Hasta :");
        jPanel1.add(lblTituloHasta);
        lblTituloHasta.setBounds(400, 330, 60, 25);

        lblTituloFechaMedicamentos.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblTituloFechaMedicamentos.setText("Fecha :");
        jPanel1.add(lblTituloFechaMedicamentos);
        lblTituloFechaMedicamentos.setBounds(400, 290, 60, 25);

        lblNoDocumento.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblNoDocumento.setText("xxxxx");
        jPanel1.add(lblNoDocumento);
        lblNoDocumento.setBounds(560, 130, 180, 27);

        lblPaciente.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblPaciente.setText("xxxxx");
        jPanel1.add(lblPaciente);
        lblPaciente.setBounds(510, 90, 220, 27);

        lblFechaMedicamentos.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblFechaMedicamentos.setText("xxxxx");
        jPanel1.add(lblFechaMedicamentos);
        lblFechaMedicamentos.setBounds(470, 290, 270, 27);

        lblEspecialidad.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblEspecialidad.setText("xxxxx");
        jPanel1.add(lblEspecialidad);
        lblEspecialidad.setBounds(530, 170, 210, 27);

        lblPlanTratamientos.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblPlanTratamientos.setText("xxxxx");
        jPanel1.add(lblPlanTratamientos);
        lblPlanTratamientos.setBounds(600, 210, 150, 27);

        lblMedicamentos.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblMedicamentos.setText("xxxxx");
        jPanel1.add(lblMedicamentos);
        lblMedicamentos.setBounds(543, 250, 200, 27);

        lblTituloFecha.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloFecha.setText("Fecha : ");
        jPanel1.add(lblTituloFecha);
        lblTituloFecha.setBounds(90, 90, 70, 27);

        lblHasta.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblHasta.setText("xxxxx");
        jPanel1.add(lblHasta);
        lblHasta.setBounds(480, 330, 260, 27);

        lblFecha.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblFecha.setText("xxxxx");
        jPanel1.add(lblFecha);
        lblFecha.setBounds(163, 90, 230, 27);

        lblTituloMotivoConsulta.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloMotivoConsulta.setText("<html>Motivo de <p>la consulta :</html>");
        jPanel1.add(lblTituloMotivoConsulta);
        lblTituloMotivoConsulta.setBounds(90, 170, 111, 54);

        lblTitulo.setFont(new java.awt.Font("Sylfaen", 1, 38)); // NOI18N
        lblTitulo.setText("Ver Historia Clinica");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(80, 30, 343, 50);

        lblTituloDiagnostico.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        lblTituloDiagnostico.setText("Diagnostico :");
        jPanel1.add(lblTituloDiagnostico);
        lblTituloDiagnostico.setBounds(90, 130, 119, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAntecedentes;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaMedicamentos;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JLabel lblMedicamentos;
    private javax.swing.JLabel lblMotivoConsulta;
    private javax.swing.JLabel lblNoDocumento;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblPlanTratamientos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloAntecedentes;
    private javax.swing.JLabel lblTituloDiagnostico;
    private javax.swing.JLabel lblTituloEspecialidad;
    private javax.swing.JLabel lblTituloFecha;
    private javax.swing.JLabel lblTituloFechaMedicamentos;
    private javax.swing.JLabel lblTituloHasta;
    private javax.swing.JLabel lblTituloMedicamentos;
    private javax.swing.JLabel lblTituloMotivoConsulta;
    private javax.swing.JLabel lblTituloNoDocumento;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloPaciente;
    private javax.swing.JLabel lblTituloPlanTratamientos;
    // End of variables declaration//GEN-END:variables
}
