/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import javax.swing.JDesktopPane;

/**
 *
 * @author marti
 */
public class Menu_Doctor_Diagnosticos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu_Doctor_Diagnosticos
     */
    public Menu_Doctor_Diagnosticos() {
        initComponents();
    }

    Menu_Doctor_Diagnosticos(JDesktopPane escritorio) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblListaDiagnosticos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnIniciarSesion2 = new javax.swing.JButton();
        btnIniciarSesion3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Diagnostico");
        setPreferredSize(new java.awt.Dimension(1099, 664));

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblListaDiagnosticos.setBackground(new java.awt.Color(255, 255, 255));
        lblListaDiagnosticos.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblListaDiagnosticos.setText("Lista Diagnosticos");
        lblListaDiagnosticos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListaDiagnosticosMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblListaDiagnosticos);
        lblListaDiagnosticos.setBounds(70, 40, 230, 34);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        FondoPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(70, 120, 960, 360);

        lblBuscar.setBackground(new java.awt.Color(255, 255, 255));
        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblBuscar.setText("Buscar :");
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblBuscar);
        lblBuscar.setBounds(680, 40, 100, 34);
        FondoPrincipal.add(txtBuscar);
        txtBuscar.setBounds(790, 30, 220, 50);

        btnIniciarSesion2.setBackground(new java.awt.Color(173, 220, 255));
        btnIniciarSesion2.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        btnIniciarSesion2.setText("Eliminar");
        btnIniciarSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesion2ActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnIniciarSesion2);
        btnIniciarSesion2.setBounds(890, 510, 139, 45);

        btnIniciarSesion3.setBackground(new java.awt.Color(173, 220, 255));
        btnIniciarSesion3.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        btnIniciarSesion3.setText("Registrar");
        btnIniciarSesion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesion3ActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnIniciarSesion3);
        btnIniciarSesion3.setBounds(710, 510, 150, 45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblListaDiagnosticosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDiagnosticosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblListaDiagnosticosMouseClicked

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void btnIniciarSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesion2ActionPerformed

    }//GEN-LAST:event_btnIniciarSesion2ActionPerformed

    private void btnIniciarSesion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesion3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnIniciarSesion1;
    private javax.swing.JButton btnIniciarSesion2;
    private javax.swing.JButton btnIniciarSesion3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblListaDiagnosticos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
