    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.HistoriaClinicaDAO;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marti
 */
public class Menu_Doctor_Historia_Clinica extends javax.swing.JInternalFrame {
    private JDesktopPane escritorio; 

    /**
     * Creates new form Menu_Doctor_Diagnosticos
     */
    public Menu_Doctor_Historia_Clinica(JDesktopPane escritorio) {
        initComponents();
         this.escritorio = escritorio;
         cargarHistoriasClinicas();
    }
    
    private void cargarHistoriasClinicas() {
        // Obtener el modelo de la tabla con los datos de las historias clínicas
        DefaultTableModel modelo = HistoriaClinicaDAO.obtenerHistoriasClinicas();
        // Establecer el modelo de la tabla
        jTable1.setModel(modelo);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblHistoriasClinicas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Historias Clinicas");
        setPreferredSize(new java.awt.Dimension(1099, 664));

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblHistoriasClinicas.setBackground(new java.awt.Color(255, 255, 255));
        lblHistoriasClinicas.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblHistoriasClinicas.setText("Lista de Historias");
        lblHistoriasClinicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHistoriasClinicasMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblHistoriasClinicas);
        lblHistoriasClinicas.setBounds(70, 40, 300, 34);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        FondoPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(70, 120, 960, 400);

        lblBuscar.setBackground(new java.awt.Color(255, 255, 255));
        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblBuscar.setText("Buscar :");
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblBuscar);
        lblBuscar.setBounds(680, 40, 100, 34);
        FondoPrincipal.add(txtBuscar);
        txtBuscar.setBounds(790, 30, 220, 50);

        btnRegistrar.setBackground(new java.awt.Color(173, 220, 255));
        btnRegistrar.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnRegistrar);
        btnRegistrar.setBounds(710, 540, 150, 45);

        btnVer.setBackground(new java.awt.Color(173, 220, 255));
        btnVer.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnVer);
        btnVer.setBounds(910, 540, 110, 45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHistoriasClinicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoriasClinicasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHistoriasClinicasMouseClicked

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        Menu_Doctor_Historia_Clinica_Registrar verventana = new Menu_Doctor_Historia_Clinica_Registrar();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
           int selectedRow = jTable1.getSelectedRow();

        // Verificar si hay una fila seleccionada
        if (selectedRow != -1) {
        // Obtener el historiaId desde la tabla (asumiendo que es la primera columna o la columna oculta)
        int historiaId = (int) jTable1.getValueAt(selectedRow, 0); // Ajusta el índice según la columna de historiaId

        // Crear una nueva ventana para ver la historia clínica con el historiaId
        Menu_Doctor_Historia_Clinica_VerHistoria ventanaVerHistoria = new Menu_Doctor_Historia_Clinica_VerHistoria(historiaId);
        
        // Agregar la ventana al escritorio
        escritorio.add(ventanaVerHistoria);
        ventanaVerHistoria.show();
        } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila.");
        }
    }//GEN-LAST:event_btnVerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblHistoriasClinicas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
