/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author marti
 */
public class Menu_Doctor extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Doctor
     */
    public Menu_Doctor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        FondoHorizontal = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        FondoVertical = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        lblPacientes = new javax.swing.JLabel();
        lblDiagnósticos = new javax.swing.JLabel();
        lblCitasAgendadas = new javax.swing.JLabel();
        lblHistoriasClinicas = new javax.swing.JLabel();
        FondoPrincipal = new javax.swing.JPanel();
        TotalDiagnosticos = new javax.swing.JPanel();
        lblTotalDiagnosticos = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        TotalPacientesPanel = new javax.swing.JPanel();
        lblTotalPacientes = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        TotalHistorias = new javax.swing.JPanel();
        lblTotalHistorias = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        FondoHorizontal.setBackground(new java.awt.Color(220, 233, 255));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Logos/Logo_Descripcion.png"))); // NOI18N
        imgLogo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout FondoHorizontalLayout = new javax.swing.GroupLayout(FondoHorizontal);
        FondoHorizontal.setLayout(FondoHorizontalLayout);
        FondoHorizontalLayout.setHorizontalGroup(
            FondoHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoHorizontalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1006, Short.MAX_VALUE))
        );
        FondoHorizontalLayout.setVerticalGroup(
            FondoHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoHorizontalLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        escritorio.add(FondoHorizontal);
        FondoHorizontal.setBounds(0, 0, 1327, 140);

        FondoVertical.setBackground(new java.awt.Color(220, 233, 255));

        lblDashboard.setBackground(new java.awt.Color(255, 255, 255));
        lblDashboard.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });

        lblPacientes.setBackground(new java.awt.Color(255, 255, 255));
        lblPacientes.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblPacientes.setText("Pacientes");
        lblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPacientesMouseClicked(evt);
            }
        });

        lblDiagnósticos.setBackground(new java.awt.Color(255, 255, 255));
        lblDiagnósticos.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblDiagnósticos.setText("Diagnósticos");
        lblDiagnósticos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDiagnósticosMouseClicked(evt);
            }
        });

        lblCitasAgendadas.setBackground(new java.awt.Color(255, 255, 255));
        lblCitasAgendadas.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblCitasAgendadas.setText("<html>Citas <p>Agendadas<html>");
        lblCitasAgendadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCitasAgendadasMouseClicked(evt);
            }
        });

        lblHistoriasClinicas.setBackground(new java.awt.Color(255, 255, 255));
        lblHistoriasClinicas.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblHistoriasClinicas.setText("<html>Historias <p>Clínicas</html>");
        lblHistoriasClinicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHistoriasClinicasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FondoVerticalLayout = new javax.swing.GroupLayout(FondoVertical);
        FondoVertical.setLayout(FondoVerticalLayout);
        FondoVerticalLayout.setHorizontalGroup(
            FondoVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerticalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCitasAgendadas, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDashboard)
                    .addComponent(lblPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiagnósticos)
                    .addComponent(lblHistoriasClinicas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        FondoVerticalLayout.setVerticalGroup(
            FondoVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerticalLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblDashboard)
                .addGap(40, 40, 40)
                .addComponent(lblPacientes)
                .addGap(47, 47, 47)
                .addComponent(lblDiagnósticos)
                .addGap(36, 36, 36)
                .addComponent(lblCitasAgendadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lblHistoriasClinicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        escritorio.add(FondoVertical);
        FondoVertical.setBounds(0, 140, 220, 570);

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        TotalDiagnosticos.setBackground(new java.awt.Color(173, 220, 255));
        TotalDiagnosticos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalDiagnosticosMouseClicked(evt);
            }
        });

        lblTotalDiagnosticos.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalDiagnosticos.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTotalDiagnosticos.setText("Total Diagnósticos");
        lblTotalDiagnosticos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTotalDiagnosticosMouseClicked(evt);
            }
        });

        lbl2.setBackground(new java.awt.Color(255, 255, 255));
        lbl2.setFont(new java.awt.Font("Sylfaen", 1, 65)); // NOI18N
        lbl2.setText("2");
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TotalDiagnosticosLayout = new javax.swing.GroupLayout(TotalDiagnosticos);
        TotalDiagnosticos.setLayout(TotalDiagnosticosLayout);
        TotalDiagnosticosLayout.setHorizontalGroup(
            TotalDiagnosticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalDiagnosticosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalDiagnosticos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalDiagnosticosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl2)
                .addGap(114, 114, 114))
        );
        TotalDiagnosticosLayout.setVerticalGroup(
            TotalDiagnosticosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalDiagnosticosLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(lbl2)
                .addGap(18, 18, 18)
                .addComponent(lblTotalDiagnosticos)
                .addGap(21, 21, 21))
        );

        FondoPrincipal.add(TotalDiagnosticos);
        TotalDiagnosticos.setBounds(430, 40, 260, 210);

        TotalPacientesPanel.setBackground(new java.awt.Color(173, 220, 255));
        TotalPacientesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalPacientesPanelMouseClicked(evt);
            }
        });

        lblTotalPacientes.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalPacientes.setFont(new java.awt.Font("Sylfaen", 1, 35)); // NOI18N
        lblTotalPacientes.setText("Total Pacientes");
        lblTotalPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTotalPacientesMouseClicked(evt);
            }
        });

        lbl1.setBackground(new java.awt.Color(255, 255, 255));
        lbl1.setFont(new java.awt.Font("Sylfaen", 1, 65)); // NOI18N
        lbl1.setText("1");
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TotalPacientesPanelLayout = new javax.swing.GroupLayout(TotalPacientesPanel);
        TotalPacientesPanel.setLayout(TotalPacientesPanelLayout);
        TotalPacientesPanelLayout.setHorizontalGroup(
            TotalPacientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPacientesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalPacientes)
                .addGap(32, 32, 32))
            .addGroup(TotalPacientesPanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lbl1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TotalPacientesPanelLayout.setVerticalGroup(
            TotalPacientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalPacientesPanelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalPacientes)
                .addGap(19, 19, 19))
        );

        FondoPrincipal.add(TotalPacientesPanel);
        TotalPacientesPanel.setBounds(70, 40, 260, 210);

        TotalHistorias.setBackground(new java.awt.Color(173, 220, 255));
        TotalHistorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalHistoriasMouseClicked(evt);
            }
        });

        lblTotalHistorias.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalHistorias.setFont(new java.awt.Font("Sylfaen", 1, 35)); // NOI18N
        lblTotalHistorias.setText("Total Historias");
        lblTotalHistorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTotalHistoriasMouseClicked(evt);
            }
        });

        lbl3.setBackground(new java.awt.Color(255, 255, 255));
        lbl3.setFont(new java.awt.Font("Sylfaen", 1, 65)); // NOI18N
        lbl3.setText("3");
        lbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TotalHistoriasLayout = new javax.swing.GroupLayout(TotalHistorias);
        TotalHistorias.setLayout(TotalHistoriasLayout);
        TotalHistoriasLayout.setHorizontalGroup(
            TotalHistoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalHistoriasLayout.createSequentialGroup()
                .addGroup(TotalHistoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TotalHistoriasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTotalHistorias))
                    .addGroup(TotalHistoriasLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lbl3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TotalHistoriasLayout.setVerticalGroup(
            TotalHistoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalHistoriasLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbl3)
                .addGap(18, 18, 18)
                .addComponent(lblTotalHistorias)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        FondoPrincipal.add(TotalHistorias);
        TotalHistorias.setBounds(790, 40, 254, 210);

        escritorio.add(FondoPrincipal);
        FondoPrincipal.setBounds(220, 140, 1110, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1327, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        // TODO add your handling code here:
        Menu_Doctor_Dasbhoard verventana=new Menu_Doctor_Dasbhoard();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPacientesMouseClicked
        // TODO add your handling code here:
        Menu_Doctor_TotalPacientes verventana = new Menu_Doctor_TotalPacientes(escritorio);
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_lblPacientesMouseClicked

    private void lblDiagnósticosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiagnósticosMouseClicked
        // TODO add your handling code here:
        Menu_Doctor_Diagnosticos verventana=new Menu_Doctor_Diagnosticos();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_lblDiagnósticosMouseClicked

    private void lblCitasAgendadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCitasAgendadasMouseClicked
        // TODO add your handling code here:
        Menu_Doctor_Citas verventana=new Menu_Doctor_Citas();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_lblCitasAgendadasMouseClicked

    private void lblHistoriasClinicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoriasClinicasMouseClicked
        // TODO add your handling code here:
        Menu_Doctor_Historia_Clinica verventana=new Menu_Doctor_Historia_Clinica();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_lblHistoriasClinicasMouseClicked

    private void lblTotalPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotalPacientesMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblTotalPacientesMouseClicked

    private void lblTotalDiagnosticosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotalDiagnosticosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotalDiagnosticosMouseClicked

    private void lblTotalHistoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotalHistoriasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotalHistoriasMouseClicked

    private void lbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl1MouseClicked

    private void lbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl3MouseClicked

    private void lbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl2MouseClicked

    private void TotalPacientesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalPacientesPanelMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TotalPacientesPanelMouseClicked

    private void TotalDiagnosticosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalDiagnosticosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalDiagnosticosMouseClicked

    private void TotalHistoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalHistoriasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHistoriasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoHorizontal;
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JPanel FondoVertical;
    private javax.swing.JPanel TotalDiagnosticos;
    private javax.swing.JPanel TotalHistorias;
    private javax.swing.JPanel TotalPacientesPanel;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblCitasAgendadas;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDiagnósticos;
    private javax.swing.JLabel lblHistoriasClinicas;
    private javax.swing.JLabel lblPacientes;
    private javax.swing.JLabel lblTotalDiagnosticos;
    private javax.swing.JLabel lblTotalHistorias;
    private javax.swing.JLabel lblTotalPacientes;
    // End of variables declaration//GEN-END:variables
}
