/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAcciones;
import javax.swing.table.TableColumn;



/**
 *
 * @author marti
 */
public class Menu_Paciente_Cancelar_Cita_Agendada extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu_Doctor_TotalPacientes
     */
    public Menu_Paciente_Cancelar_Cita_Agendada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblCancelarCitaAgendada = new javax.swing.JLabel();
        lblTituloFecha = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTituloHora = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblTituloMedico = new javax.swing.JLabel();
        lblMedico = new javax.swing.JLabel();
        lblTituloEspecialidad = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        btnCancelarCitaMedica = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cancelar Cita Medica");
        setPreferredSize(new java.awt.Dimension(764, 485));

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblCancelarCitaAgendada.setBackground(new java.awt.Color(255, 255, 255));
        lblCancelarCitaAgendada.setFont(new java.awt.Font("Sylfaen", 1, 38)); // NOI18N
        lblCancelarCitaAgendada.setText("Cancelar Cita Agendada");
        lblCancelarCitaAgendada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarCitaAgendadaMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblCancelarCitaAgendada);
        lblCancelarCitaAgendada.setBounds(180, 20, 420, 70);

        lblTituloFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloFecha.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloFecha.setText("Fecha");
        lblTituloFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloFechaMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloFecha);
        lblTituloFecha.setBounds(130, 140, 90, 34);

        lblFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblFecha.setText("xx/xx/xxxx");
        lblFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFechaMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblFecha);
        lblFecha.setBounds(110, 170, 136, 34);

        lblTituloHora.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloHora.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloHora.setText("Hora");
        lblTituloHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloHoraMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloHora);
        lblTituloHora.setBounds(530, 140, 70, 34);

        lblHora.setBackground(new java.awt.Color(255, 255, 255));
        lblHora.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblHora.setText("XX:XX");
        lblHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoraMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblHora);
        lblHora.setBounds(520, 170, 80, 34);

        lblTituloMedico.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloMedico.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloMedico.setText("Médico");
        lblTituloMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloMedicoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloMedico);
        lblTituloMedico.setBounds(120, 280, 100, 34);

        lblMedico.setBackground(new java.awt.Color(255, 255, 255));
        lblMedico.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblMedico.setText("XXXXXXXX");
        lblMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMedicoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblMedico);
        lblMedico.setBounds(110, 320, 140, 34);

        lblTituloEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloEspecialidad.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloEspecialidad.setText("Especialidad");
        lblTituloEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloEspecialidadMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloEspecialidad);
        lblTituloEspecialidad.setBounds(490, 280, 180, 34);

        lblEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        lblEspecialidad.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblEspecialidad.setText("XXXXXXXXXXX");
        lblEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEspecialidadMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblEspecialidad);
        lblEspecialidad.setBounds(480, 320, 200, 34);

        btnCancelarCitaMedica.setBackground(new java.awt.Color(173, 220, 255));
        btnCancelarCitaMedica.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        btnCancelarCitaMedica.setText("Cancelar Cita Médica");
        btnCancelarCitaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCitaMedicaActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnCancelarCitaMedica);
        btnCancelarCitaMedica.setBounds(250, 400, 230, 34);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCancelarCitaAgendadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarCitaAgendadaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancelarCitaAgendadaMouseClicked

    private void lblTituloFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloFechaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloFechaMouseClicked

    private void lblFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFechaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFechaMouseClicked

    private void lblTituloHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloHoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloHoraMouseClicked

    private void lblHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHoraMouseClicked

    private void lblTituloMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMedicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloMedicoMouseClicked

    private void lblMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMedicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMedicoMouseClicked

    private void lblTituloEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloEspecialidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloEspecialidadMouseClicked

    private void lblEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEspecialidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEspecialidadMouseClicked

    private void btnCancelarCitaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCitaMedicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarCitaMedicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JButton btnCancelarCitaMedica;
    private javax.swing.JLabel lblCancelarCitaAgendada;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblTituloEspecialidad;
    private javax.swing.JLabel lblTituloFecha;
    private javax.swing.JLabel lblTituloHora;
    private javax.swing.JLabel lblTituloMedico;
    // End of variables declaration//GEN-END:variables
}
