/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAcciones;
import Modelo.Paciente;
import javax.swing.table.TableColumn;



/**
 *
 * @author marti
 */
public class Menu_Doctor_VerPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu_Doctor_TotalPacientes
     */
    public Menu_Doctor_VerPacientes() {
        initComponents();
    }
    
    public void cargarDatosPaciente(String documento) {
    ControladorAcciones controlador = new ControladorAcciones();
    Paciente p = controlador.obtenerPacientePorDocumento(documento);

        if (p != null) {
          lblNombreTitulo.setText(p.getNombres());
          lblNombre.setText(p.getNombres());
          lblApellido.setText(p.getApellidos());
          lblTipoDocumento.setText(p.getTipoDocumento());
          lblNoDocumento.setText(p.getDocumento());
          lblFechaNacimiento.setText(p.getFechaNacimiento());
          lblGenero.setText(p.getGenero());
          lblTipoSangre.setText(p.getTipoSangre());
          lblAlergias.setText(p.getAlergias());
          lblEnfermedadesCronicas.setText(p.getEnfermedadesCronicas());
          lblCelular.setText(p.getCelular());
          lblEmail.setText(p.getEmail());
          lblOcupacion.setText(p.getOcupacion());
          lblDireccion.setText(p.getDireccion());
          lblEPS.setText(p.getEps());
    } else {
        System.out.println("No se encontró el paciente con documento: " + documento);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblVerPaciente = new javax.swing.JLabel();
        lblNombreTitulo = new javax.swing.JLabel();
        lblTituloNombre = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTituloTipoDocumento = new javax.swing.JLabel();
        lblTipoDocumento = new javax.swing.JLabel();
        lblTituloFechaNacimiento = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblTituloGenero = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblTituloTipoSangre = new javax.swing.JLabel();
        lblTipoSangre = new javax.swing.JLabel();
        lblEnfermedadesCronicas = new javax.swing.JLabel();
        lblTituloEnfermedadesCronicas = new javax.swing.JLabel();
        lblTituloApellido = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNoDocumento = new javax.swing.JLabel();
        lblTituloNoDocumento = new javax.swing.JLabel();
        lblOcupacion = new javax.swing.JLabel();
        lblTituloOcupacion = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblTituloCelular = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTituloDireccion = new javax.swing.JLabel();
        lblEPS = new javax.swing.JLabel();
        lblTituloEPS = new javax.swing.JLabel();
        lblAlergias = new javax.swing.JLabel();
        lblTituloAlergias = new javax.swing.JLabel();
        lblTituloEmail = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("VerPacientes");
        setPreferredSize(new java.awt.Dimension(1099, 664));

        FondoPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        FondoPrincipal.setLayout(null);

        lblVerPaciente.setBackground(new java.awt.Color(255, 255, 255));
        lblVerPaciente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblVerPaciente.setText("Ver Paciente:");
        lblVerPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerPacienteMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblVerPaciente);
        lblVerPaciente.setBounds(50, 30, 260, 70);

        lblNombreTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblNombreTitulo.setText("Nombre");
        lblNombreTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNombreTituloMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblNombreTitulo);
        lblNombreTitulo.setBounds(310, 50, 350, 34);

        lblTituloNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloNombre.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloNombre.setText("Nombre :");
        lblTituloNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloNombreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloNombre);
        lblTituloNombre.setBounds(40, 130, 120, 34);

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblNombre.setText("Nombre");
        lblNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNombreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblNombre);
        lblNombre.setBounds(170, 130, 120, 34);

        lblTituloTipoDocumento.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloTipoDocumento.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloTipoDocumento.setText("Tipo de documento :");
        lblTituloTipoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloTipoDocumentoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloTipoDocumento);
        lblTituloTipoDocumento.setBounds(40, 200, 270, 34);

        lblTipoDocumento.setBackground(new java.awt.Color(255, 255, 255));
        lblTipoDocumento.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTipoDocumento.setText("Tipo de documento");
        lblTipoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTipoDocumentoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTipoDocumento);
        lblTipoDocumento.setBounds(320, 200, 250, 34);

        lblTituloFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloFechaNacimiento.setText("Fecha de nacimiento :");
        lblTituloFechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloFechaNacimientoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloFechaNacimiento);
        lblTituloFechaNacimiento.setBounds(40, 260, 270, 34);

        lblFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblFechaNacimiento.setText("Fecha de nacimiento");
        lblFechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFechaNacimientoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblFechaNacimiento);
        lblFechaNacimiento.setBounds(320, 260, 250, 34);

        lblTituloGenero.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloGenero.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloGenero.setText("Genero:");
        lblTituloGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloGeneroMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloGenero);
        lblTituloGenero.setBounds(40, 320, 110, 34);

        lblGenero.setBackground(new java.awt.Color(255, 255, 255));
        lblGenero.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblGenero.setText("Fecha de nacimiento");
        lblGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGeneroMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblGenero);
        lblGenero.setBounds(160, 320, 250, 34);

        lblTituloTipoSangre.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloTipoSangre.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloTipoSangre.setText("Tipo de sangre :");
        lblTituloTipoSangre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloTipoSangreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloTipoSangre);
        lblTituloTipoSangre.setBounds(40, 380, 200, 34);

        lblTipoSangre.setBackground(new java.awt.Color(255, 255, 255));
        lblTipoSangre.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTipoSangre.setText("Tipo de sangre");
        lblTipoSangre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTipoSangreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTipoSangre);
        lblTipoSangre.setBounds(250, 380, 250, 34);

        lblEnfermedadesCronicas.setBackground(new java.awt.Color(255, 255, 255));
        lblEnfermedadesCronicas.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblEnfermedadesCronicas.setText("Enfermedades crónicas");
        lblEnfermedadesCronicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnfermedadesCronicasMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblEnfermedadesCronicas);
        lblEnfermedadesCronicas.setBounds(40, 560, 500, 34);

        lblTituloEnfermedadesCronicas.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloEnfermedadesCronicas.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloEnfermedadesCronicas.setText("Enfermedades crónicas :");
        lblTituloEnfermedadesCronicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloEnfermedadesCronicasMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloEnfermedadesCronicas);
        lblTituloEnfermedadesCronicas.setBounds(40, 510, 300, 34);

        lblTituloApellido.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloApellido.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloApellido.setText("Apellido :");
        lblTituloApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloApellidoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloApellido);
        lblTituloApellido.setBounds(580, 130, 120, 34);

        lblApellido.setBackground(new java.awt.Color(255, 255, 255));
        lblApellido.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblApellido.setText("Fecha de nacimiento");
        lblApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblApellidoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblApellido);
        lblApellido.setBounds(720, 130, 310, 34);

        lblNoDocumento.setBackground(new java.awt.Color(255, 255, 255));
        lblNoDocumento.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblNoDocumento.setText("N° Documento");
        lblNoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNoDocumentoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblNoDocumento);
        lblNoDocumento.setBounds(790, 200, 280, 34);

        lblTituloNoDocumento.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloNoDocumento.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloNoDocumento.setText("N° Documento :");
        lblTituloNoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloNoDocumentoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloNoDocumento);
        lblTituloNoDocumento.setBounds(580, 200, 200, 34);

        lblOcupacion.setBackground(new java.awt.Color(255, 255, 255));
        lblOcupacion.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblOcupacion.setText("Ocupación");
        lblOcupacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOcupacionMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblOcupacion);
        lblOcupacion.setBounds(740, 260, 280, 34);

        lblTituloOcupacion.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloOcupacion.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloOcupacion.setText("Ocupación :");
        lblTituloOcupacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloOcupacionMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloOcupacion);
        lblTituloOcupacion.setBounds(580, 260, 160, 34);

        lblCelular.setBackground(new java.awt.Color(255, 255, 255));
        lblCelular.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblCelular.setText("Celular");
        lblCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCelularMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblCelular);
        lblCelular.setBounds(700, 320, 350, 34);

        lblTituloCelular.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloCelular.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloCelular.setText("Celular :");
        lblTituloCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloCelularMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloCelular);
        lblTituloCelular.setBounds(580, 320, 110, 34);

        lblDireccion.setBackground(new java.awt.Color(255, 255, 255));
        lblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblDireccion.setText("Dirección");
        lblDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDireccionMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblDireccion);
        lblDireccion.setBounds(580, 420, 490, 34);

        lblTituloDireccion.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloDireccion.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloDireccion.setText("Dirección :");
        lblTituloDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloDireccionMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloDireccion);
        lblTituloDireccion.setBounds(580, 380, 140, 34);

        lblEPS.setBackground(new java.awt.Color(255, 255, 255));
        lblEPS.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblEPS.setText("EPS");
        lblEPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEPSMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblEPS);
        lblEPS.setBounds(660, 470, 400, 34);

        lblTituloEPS.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloEPS.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloEPS.setText("EPS :");
        lblTituloEPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloEPSMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloEPS);
        lblTituloEPS.setBounds(580, 470, 70, 34);

        lblAlergias.setBackground(new java.awt.Color(255, 255, 255));
        lblAlergias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAlergias.setText("Alergias");
        lblAlergias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlergiasMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblAlergias);
        lblAlergias.setBounds(40, 470, 440, 34);

        lblTituloAlergias.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloAlergias.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloAlergias.setText("Alergias :");
        lblTituloAlergias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloAlergiasMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloAlergias);
        lblTituloAlergias.setBounds(40, 430, 120, 34);

        lblTituloEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloEmail.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloEmail.setText("Email :");
        lblTituloEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloEmailMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloEmail);
        lblTituloEmail.setBounds(580, 520, 90, 34);

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmailMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblEmail);
        lblEmail.setBounds(680, 520, 380, 34);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVerPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVerPacienteMouseClicked

    private void lblNombreTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNombreTituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNombreTituloMouseClicked

    private void lblTituloNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloNombreMouseClicked

    private void lblNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNombreMouseClicked

    private void lblTituloTipoDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloTipoDocumentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloTipoDocumentoMouseClicked

    private void lblTipoDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTipoDocumentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTipoDocumentoMouseClicked

    private void lblTituloFechaNacimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloFechaNacimientoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloFechaNacimientoMouseClicked

    private void lblFechaNacimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFechaNacimientoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFechaNacimientoMouseClicked

    private void lblTituloGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloGeneroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloGeneroMouseClicked

    private void lblGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGeneroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGeneroMouseClicked

    private void lblTituloTipoSangreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloTipoSangreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloTipoSangreMouseClicked

    private void lblTipoSangreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTipoSangreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTipoSangreMouseClicked

    private void lblEnfermedadesCronicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnfermedadesCronicasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEnfermedadesCronicasMouseClicked

    private void lblTituloEnfermedadesCronicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloEnfermedadesCronicasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloEnfermedadesCronicasMouseClicked

    private void lblTituloApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloApellidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloApellidoMouseClicked

    private void lblApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApellidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblApellidoMouseClicked

    private void lblNoDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoDocumentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNoDocumentoMouseClicked

    private void lblTituloNoDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloNoDocumentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloNoDocumentoMouseClicked

    private void lblOcupacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOcupacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOcupacionMouseClicked

    private void lblTituloOcupacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloOcupacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloOcupacionMouseClicked

    private void lblCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCelularMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCelularMouseClicked

    private void lblTituloCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloCelularMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloCelularMouseClicked

    private void lblDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDireccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDireccionMouseClicked

    private void lblTituloDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloDireccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloDireccionMouseClicked

    private void lblEPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEPSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEPSMouseClicked

    private void lblTituloEPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloEPSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloEPSMouseClicked

    private void lblAlergiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlergiasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAlergiasMouseClicked

    private void lblTituloAlergiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloAlergiasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloAlergiasMouseClicked

    private void lblTituloEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloEmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloEmailMouseClicked

    private void lblEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEmailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JLabel lblAlergias;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEPS;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnfermedadesCronicas;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNoDocumento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreTitulo;
    private javax.swing.JLabel lblOcupacion;
    private javax.swing.JLabel lblTipoDocumento;
    private javax.swing.JLabel lblTipoSangre;
    private javax.swing.JLabel lblTituloAlergias;
    private javax.swing.JLabel lblTituloApellido;
    private javax.swing.JLabel lblTituloCelular;
    private javax.swing.JLabel lblTituloDireccion;
    private javax.swing.JLabel lblTituloEPS;
    private javax.swing.JLabel lblTituloEmail;
    private javax.swing.JLabel lblTituloEnfermedadesCronicas;
    private javax.swing.JLabel lblTituloFechaNacimiento;
    private javax.swing.JLabel lblTituloGenero;
    private javax.swing.JLabel lblTituloNoDocumento;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloOcupacion;
    private javax.swing.JLabel lblTituloTipoDocumento;
    private javax.swing.JLabel lblTituloTipoSangre;
    private javax.swing.JLabel lblVerPaciente;
    // End of variables declaration//GEN-END:variables
}
