/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controlador.DoctorDAO;
import Controlador.HistoriaClinicaDAO;
import Controlador.PacienteDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class Menu_Admin extends javax.swing.JFrame {
    
    PacienteDAO pacienteDAO = new PacienteDAO();
    DoctorDAO doctorDAO = new DoctorDAO();
    

    /**
     * Creates new form Menu_Doctor
     */
    public Menu_Admin() {
        initComponents();
        this.setLocationRelativeTo(null);

        int totalPacientes = pacienteDAO.contarPacientes();

        lbl1.setText(""+totalPacientes); 
        
        int totalMedicos = doctorDAO.contarDoctores();
        
        lbl2.setText(""+totalMedicos);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        FondoHorizontal = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        FondoVertical = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        lblPacientes = new javax.swing.JLabel();
        lblMedicos = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        FondoPrincipal = new javax.swing.JPanel();
        TotalPacientesPanel = new javax.swing.JPanel();
        lblTotalPacientes = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        TotalPacientesPanel1 = new javax.swing.JPanel();
        lblTotalPacientes1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblDescripcion1 = new javax.swing.JLabel();
        lblDescripcion2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        FondoHorizontal.setBackground(new java.awt.Color(220, 233, 255));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Logos/Logo_Descripcion.png"))); // NOI18N
        imgLogo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout FondoHorizontalLayout = new javax.swing.GroupLayout(FondoHorizontal);
        FondoHorizontal.setLayout(FondoHorizontalLayout);
        FondoHorizontalLayout.setHorizontalGroup(
            FondoHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoHorizontalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1006, Short.MAX_VALUE))
        );
        FondoHorizontalLayout.setVerticalGroup(
            FondoHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoHorizontalLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        escritorio.add(FondoHorizontal);
        FondoHorizontal.setBounds(0, 0, 1327, 140);

        FondoVertical.setBackground(new java.awt.Color(220, 233, 255));

        lblDashboard.setBackground(new java.awt.Color(255, 255, 255));
        lblDashboard.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });

        lblPacientes.setBackground(new java.awt.Color(255, 255, 255));
        lblPacientes.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblPacientes.setText("Pacientes");
        lblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPacientesMouseEntered(evt);
            }
        });

        lblMedicos.setBackground(new java.awt.Color(255, 255, 255));
        lblMedicos.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblMedicos.setText("Médicos");
        lblMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMedicosMouseClicked(evt);
            }
        });

        lblCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblCerrarSesion.setText("Cerrar Sesion");
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FondoVerticalLayout = new javax.swing.GroupLayout(FondoVertical);
        FondoVertical.setLayout(FondoVerticalLayout);
        FondoVerticalLayout.setHorizontalGroup(
            FondoVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerticalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDashboard)
                    .addComponent(lblMedicos)
                    .addComponent(lblPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCerrarSesion))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        FondoVerticalLayout.setVerticalGroup(
            FondoVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerticalLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblDashboard)
                .addGap(56, 56, 56)
                .addComponent(lblMedicos)
                .addGap(54, 54, 54)
                .addComponent(lblPacientes)
                .addGap(58, 58, 58)
                .addComponent(lblCerrarSesion)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        escritorio.add(FondoVertical);
        FondoVertical.setBounds(0, 140, 220, 570);

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        TotalPacientesPanel.setBackground(new java.awt.Color(173, 220, 255));
        TotalPacientesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalPacientesPanelMouseClicked(evt);
            }
        });

        lblTotalPacientes.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalPacientes.setFont(new java.awt.Font("Sylfaen", 1, 35)); // NOI18N
        lblTotalPacientes.setText("Total Pacientes");
        lblTotalPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTotalPacientesMouseClicked(evt);
            }
        });

        lbl1.setBackground(new java.awt.Color(255, 255, 255));
        lbl1.setFont(new java.awt.Font("Sylfaen", 1, 65)); // NOI18N
        lbl1.setText("X");
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TotalPacientesPanelLayout = new javax.swing.GroupLayout(TotalPacientesPanel);
        TotalPacientesPanel.setLayout(TotalPacientesPanelLayout);
        TotalPacientesPanelLayout.setHorizontalGroup(
            TotalPacientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPacientesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalPacientes)
                .addGap(32, 32, 32))
            .addGroup(TotalPacientesPanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lbl1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TotalPacientesPanelLayout.setVerticalGroup(
            TotalPacientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalPacientesPanelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalPacientes)
                .addGap(19, 19, 19))
        );

        FondoPrincipal.add(TotalPacientesPanel);
        TotalPacientesPanel.setBounds(630, 150, 260, 210);

        TotalPacientesPanel1.setBackground(new java.awt.Color(173, 220, 255));
        TotalPacientesPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalPacientesPanel1MouseClicked(evt);
            }
        });

        lblTotalPacientes1.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalPacientes1.setFont(new java.awt.Font("Sylfaen", 1, 35)); // NOI18N
        lblTotalPacientes1.setText("Total Medicos");
        lblTotalPacientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTotalPacientes1MouseClicked(evt);
            }
        });

        lbl2.setBackground(new java.awt.Color(255, 255, 255));
        lbl2.setFont(new java.awt.Font("Sylfaen", 1, 65)); // NOI18N
        lbl2.setText("X");
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TotalPacientesPanel1Layout = new javax.swing.GroupLayout(TotalPacientesPanel1);
        TotalPacientesPanel1.setLayout(TotalPacientesPanel1Layout);
        TotalPacientesPanel1Layout.setHorizontalGroup(
            TotalPacientesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPacientesPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lbl2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalPacientesPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblTotalPacientes1)
                .addGap(17, 17, 17))
        );
        TotalPacientesPanel1Layout.setVerticalGroup(
            TotalPacientesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalPacientesPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(lbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPacientes1)
                .addGap(25, 25, 25))
        );

        FondoPrincipal.add(TotalPacientesPanel1);
        TotalPacientesPanel1.setBounds(230, 150, 260, 210);

        lblDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        lblDescripcion.setText("Bienvenido , administrador :");
        lblDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDescripcionMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblDescripcion);
        lblDescripcion.setBounds(20, 30, 460, 50);

        lblDescripcion1.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcion1.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        lblDescripcion1.setText("X");
        lblDescripcion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDescripcion1MouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblDescripcion1);
        lblDescripcion1.setBounds(490, 30, 270, 50);

        lblDescripcion2.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcion2.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        lblDescripcion2.setText("Desde aqui puedes gestionar los usuarios del sistema");
        lblDescripcion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDescripcion2MouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblDescripcion2);
        lblDescripcion2.setBounds(20, 80, 860, 50);

        escritorio.add(FondoPrincipal);
        FondoPrincipal.setBounds(220, 140, 1110, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1327, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null ,"Ya estas en el menu");
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPacientesMouseClicked
        // TODO add your handling code here:
        Menu_Admin_Pacientes verventana=new Menu_Admin_Pacientes(escritorio);
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_lblPacientesMouseClicked

    private void lblMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMedicosMouseClicked
        // TODO add your handling code here:
        Menu_Admin_Medicos verventana=new Menu_Admin_Medicos(escritorio);
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_lblMedicosMouseClicked

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        int opcion = JOptionPane.showConfirmDialog(
        this,
        "¿Quieres cerrar sesión?",
        "Confirmación",
        JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
            menu.setLocationRelativeTo(null);
            this.dispose();  
}     
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void lblTotalPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotalPacientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotalPacientesMouseClicked

    private void lbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl1MouseClicked

    private void TotalPacientesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalPacientesPanelMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TotalPacientesPanelMouseClicked

    private void lblTotalPacientes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotalPacientes1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotalPacientes1MouseClicked

    private void lbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl2MouseClicked

    private void TotalPacientesPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalPacientesPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPacientesPanel1MouseClicked

    private void lblDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescripcionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDescripcionMouseClicked

    private void lblDescripcion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescripcion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDescripcion1MouseClicked

    private void lblDescripcion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDescripcion2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDescripcion2MouseClicked

    private void lblPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPacientesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPacientesMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoHorizontal;
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JPanel FondoVertical;
    private javax.swing.JPanel TotalPacientesPanel;
    private javax.swing.JPanel TotalPacientesPanel1;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblDescripcion2;
    private javax.swing.JLabel lblMedicos;
    private javax.swing.JLabel lblPacientes;
    private javax.swing.JLabel lblTotalPacientes;
    private javax.swing.JLabel lblTotalPacientes1;
    // End of variables declaration//GEN-END:variables
}
