/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.PacienteDAO;
import Modelo.Paciente;
import javax.swing.JOptionPane;




/**
 *
 * @author marti
 */
public class Menu_Admin_Pacientes_Modificar extends javax.swing.JInternalFrame {
    private Paciente paciente;
    

    /**
     * Creates new form Menu_Doctor_TotalPacientes
     */
    public Menu_Admin_Pacientes_Modificar(Paciente paciente) {
        initComponents();
        this.paciente = paciente;
        
        lblNombre.setText(paciente.getNombres());
        
        cbTipoDocumento.setSelectedItem(paciente.getTipoDocumento());
        txtDocumento.setText(paciente.getDocumento());
        txtAreaAlergias.setText(paciente.getAlergias());
        cbEnfermedadesCronicas.setSelectedItem(paciente.getEnfermedadesCronicas());
        txtEPS.setText(paciente.getEps());
        txtCelular.setText(paciente.getCelular());
        txtEmail.setText(paciente.getEmail());
        txtDireccion.setText(paciente.getDireccion());
        txtContrasena.setText(paciente.getContrasena());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblTituloConfiguración = new javax.swing.JLabel();
        lblTituloNombre = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        cbTipoDocumento = new javax.swing.JComboBox<>();
        txtDocumento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAlergias = new javax.swing.JTextArea();
        cbEnfermedadesCronicas = new javax.swing.JComboBox<>();
        txtCelular = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEPS = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Modificar");
        setPreferredSize(new java.awt.Dimension(693, 472));

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblTituloConfiguración.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloConfiguración.setFont(new java.awt.Font("Sylfaen", 1, 38)); // NOI18N
        lblTituloConfiguración.setText("Modificar Paciente");
        lblTituloConfiguración.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloConfiguraciónMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloConfiguración);
        lblTituloConfiguración.setBounds(170, 10, 330, 50);

        lblTituloNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloNombre.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTituloNombre.setText("Nombre:");
        lblTituloNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloNombreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloNombre);
        lblTituloNombre.setBounds(30, 60, 120, 34);

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblNombre.setText("XX");
        lblNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNombreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblNombre);
        lblNombre.setBounds(150, 60, 310, 30);

        btnActualizar.setBackground(new java.awt.Color(173, 220, 255));
        btnActualizar.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbtnActualizarActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnActualizar);
        btnActualizar.setBounds(290, 390, 130, 34);

        cbTipoDocumento.setBackground(new java.awt.Color(220, 233, 255));
        cbTipoDocumento.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        cbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "C.C", "C.E", "T.I", "P.A" }));
        FondoPrincipal.add(cbTipoDocumento);
        cbTipoDocumento.setBounds(30, 100, 130, 40);

        txtDocumento.setBackground(new java.awt.Color(220, 233, 255));
        txtDocumento.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtDocumento.setText("No. Documento");
        FondoPrincipal.add(txtDocumento);
        txtDocumento.setBounds(190, 100, 345, 40);

        txtAreaAlergias.setBackground(new java.awt.Color(220, 233, 255));
        txtAreaAlergias.setColumns(20);
        txtAreaAlergias.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        txtAreaAlergias.setRows(5);
        txtAreaAlergias.setText("Alergias");
        jScrollPane1.setViewportView(txtAreaAlergias);

        FondoPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(30, 160, 220, 90);

        cbEnfermedadesCronicas.setBackground(new java.awt.Color(220, 233, 255));
        cbEnfermedadesCronicas.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        cbEnfermedadesCronicas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enfermedades Crónicas", "Cáncer", "Diabetes", "Hipertensión arterial", "Osteoartrsis", "Asma", "Artritis", "Cardiopatía", "Enfermedad Pulmonar", "Ninguna", "Otra" }));
        FondoPrincipal.add(cbEnfermedadesCronicas);
        cbEnfermedadesCronicas.setBounds(290, 160, 260, 40);

        txtCelular.setBackground(new java.awt.Color(220, 233, 255));
        txtCelular.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtCelular.setText("Celular");
        FondoPrincipal.add(txtCelular);
        txtCelular.setBounds(30, 270, 190, 40);

        txtEmail.setBackground(new java.awt.Color(220, 233, 255));
        txtEmail.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtEmail.setText("Email");
        FondoPrincipal.add(txtEmail);
        txtEmail.setBounds(290, 270, 290, 40);

        txtDireccion.setBackground(new java.awt.Color(220, 233, 255));
        txtDireccion.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtDireccion.setText("Dirección");
        FondoPrincipal.add(txtDireccion);
        txtDireccion.setBounds(30, 330, 290, 40);

        txtEPS.setBackground(new java.awt.Color(220, 233, 255));
        txtEPS.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtEPS.setText("EPS");
        FondoPrincipal.add(txtEPS);
        txtEPS.setBounds(290, 210, 190, 40);

        txtContrasena.setBackground(new java.awt.Color(220, 233, 255));
        txtContrasena.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtContrasena.setText("Contraseña");
        FondoPrincipal.add(txtContrasena);
        txtContrasena.setBounds(360, 330, 290, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTituloNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloNombreMouseClicked

    private void lblTituloConfiguraciónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloConfiguraciónMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloConfiguraciónMouseClicked

    private void lblNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNombreMouseClicked

    private void btnbtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbtnActualizarActionPerformed
        paciente.setTipoDocumento((String) cbTipoDocumento.getSelectedItem());
        paciente.setDocumento(txtDocumento.getText());
        paciente.setAlergias(txtAreaAlergias.getText());
        paciente.setEnfermedadesCronicas((String) cbEnfermedadesCronicas.getSelectedItem());
        paciente.setCelular(txtCelular.getText());
        paciente.setEps(txtEPS.getText());
        paciente.setEmail(txtEmail.getText());
        paciente.setDireccion(txtDireccion.getText());
        paciente.setContrasena(txtContrasena.getText());
        
        PacienteDAO pacientes = new PacienteDAO();
        boolean actualizado = pacientes.actualizarDatosPacienteAdmin(paciente);
        
            if(actualizado){
                JOptionPane.showMessageDialog(this, "Datos actualizados correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar los datos.");

            }
        
    }//GEN-LAST:event_btnbtnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cbEnfermedadesCronicas;
    private javax.swing.JComboBox<String> cbTipoDocumento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTituloConfiguración;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JTextArea txtAreaAlergias;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEPS;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
