/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAcciones;
import Controlador.CitaDAO;
import Modelo.CitaMedica;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;



/**
 *
 * @author marti
 */
public class Menu_Paciente_Ver_Cita_Agendada extends javax.swing.JInternalFrame {
    
    private int idCita;
    
    /**
     * Creates new form Menu_Doctor_TotalPacientes
     */
    public Menu_Paciente_Ver_Cita_Agendada() {
        initComponents();
        cargarDatosCita(idCita);
    }
    
    public Menu_Paciente_Ver_Cita_Agendada(int idCita) {
        initComponents();
        this.idCita = idCita;
        cargarDatosCita(idCita);
    }
    
    private void cargarDatosCita(int idCita) {
    CitaDAO citaDAO = new CitaDAO();
    CitaMedica cita = citaDAO.obtenerCitaPorId(idCita); 

    if (cita != null) {
        lblFecha.setText(cita.getFecha());
        lblHora.setText(cita.getHora());
        lblMedico.setText(cita.getMedico());
        lblEspecialidad.setText(cita.getEspecialidad());
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró la cita con ID: " + idCita);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblVerCitaAgendada = new javax.swing.JLabel();
        lblTituloFecha = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTituloHora = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblTituloMedico = new javax.swing.JLabel();
        lblMedico = new javax.swing.JLabel();
        lblTituloEspecialidad = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Ver Citas");
        setPreferredSize(new java.awt.Dimension(795, 438));

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblVerCitaAgendada.setBackground(new java.awt.Color(255, 255, 255));
        lblVerCitaAgendada.setFont(new java.awt.Font("Sylfaen", 1, 38)); // NOI18N
        lblVerCitaAgendada.setText("Ver Cita Agendada");
        lblVerCitaAgendada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerCitaAgendadaMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblVerCitaAgendada);
        lblVerCitaAgendada.setBounds(230, 0, 340, 70);

        lblTituloFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloFecha.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloFecha.setText("Fecha");
        lblTituloFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloFechaMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloFecha);
        lblTituloFecha.setBounds(140, 120, 90, 40);

        lblFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblFecha.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        lblFecha.setText("xx/xx/xxxx");
        lblFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFechaMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblFecha);
        lblFecha.setBounds(110, 160, 150, 34);

        lblTituloHora.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloHora.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloHora.setText("Hora");
        lblTituloHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloHoraMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloHora);
        lblTituloHora.setBounds(530, 120, 70, 34);

        lblHora.setBackground(new java.awt.Color(255, 255, 255));
        lblHora.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        lblHora.setText("XX:XX");
        lblHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoraMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblHora);
        lblHora.setBounds(520, 160, 120, 34);

        lblTituloMedico.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloMedico.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloMedico.setText("Médico");
        lblTituloMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloMedicoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloMedico);
        lblTituloMedico.setBounds(130, 270, 100, 40);

        lblMedico.setBackground(new java.awt.Color(255, 255, 255));
        lblMedico.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        lblMedico.setText("<html><center>XXXXXXXX</html>");
        lblMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMedicoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblMedico);
        lblMedico.setBounds(40, 320, 330, 30);

        lblTituloEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloEspecialidad.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloEspecialidad.setText("Especialidad");
        lblTituloEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloEspecialidadMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloEspecialidad);
        lblTituloEspecialidad.setBounds(490, 270, 200, 40);

        lblEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        lblEspecialidad.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        lblEspecialidad.setText("<html><center>XXXXXXXXXXX</html>");
        lblEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEspecialidadMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblEspecialidad);
        lblEspecialidad.setBounds(470, 310, 220, 34);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVerCitaAgendadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerCitaAgendadaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVerCitaAgendadaMouseClicked

    private void lblTituloFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloFechaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloFechaMouseClicked

    private void lblFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFechaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFechaMouseClicked

    private void lblTituloHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloHoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloHoraMouseClicked

    private void lblHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHoraMouseClicked

    private void lblTituloMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMedicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloMedicoMouseClicked

    private void lblMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMedicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMedicoMouseClicked

    private void lblTituloEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloEspecialidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloEspecialidadMouseClicked

    private void lblEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEspecialidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEspecialidadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblTituloEspecialidad;
    private javax.swing.JLabel lblTituloFecha;
    private javax.swing.JLabel lblTituloHora;
    private javax.swing.JLabel lblTituloMedico;
    private javax.swing.JLabel lblVerCitaAgendada;
    // End of variables declaration//GEN-END:variables
}
