/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAcciones;
import Modelo.Paciente;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;



/**
 *
 * @author marti
 */
public class Menu_Paciente_Configuracion extends javax.swing.JInternalFrame {
    
     private ControladorAcciones controlador = new ControladorAcciones();
     private String documentoPaciente;

    /**
     * Creates new form Menu_Doctor_TotalPacientes
     */
    public Menu_Paciente_Configuracion(JDesktopPane escritorio, String documentoPaciente) {
        initComponents();
        this.documentoPaciente = documentoPaciente;
        cargarDatosPaciente(documentoPaciente);

    }
    
    private void cargarDatosPaciente(String documento) {
    
    ControladorAcciones controlador = new ControladorAcciones();
    Paciente p = controlador.obtenerPacientePorDocumento(documento);

     if (p != null) {
            // Asigna los datos del paciente a las etiquetas
            lblNombre.setText(p.getNombres() + " " + p.getApellidos());
            lblFechaNacimiento.setText(p.getFechaNacimiento());
        } else {
            System.out.println("No se encontró el paciente con documento: " + documento);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblTituloConfiguración = new javax.swing.JLabel();
        lblTitulo2Nombre = new javax.swing.JLabel();
        lblTituloTipoDocumento = new javax.swing.JLabel();
        lblTitulo2TipoSangre = new javax.swing.JLabel();
        lblTituloEmail = new javax.swing.JLabel();
        lblTituloCelular = new javax.swing.JLabel();
        cbTipoDocumento = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblTituloTipoDocumento1 = new javax.swing.JLabel();
        lblTituloTipoDocumento2 = new javax.swing.JLabel();
        lblTituloTipoDocumento3 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtOcupacion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Configuracion");
        setPreferredSize(new java.awt.Dimension(908, 462));

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblTituloConfiguración.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloConfiguración.setFont(new java.awt.Font("Sylfaen", 1, 38)); // NOI18N
        lblTituloConfiguración.setText("Configuración");
        lblTituloConfiguración.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloConfiguraciónMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloConfiguración);
        lblTituloConfiguración.setBounds(310, 10, 250, 50);

        lblTitulo2Nombre.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo2Nombre.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTitulo2Nombre.setText("Nombre:");
        lblTitulo2Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTitulo2NombreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTitulo2Nombre);
        lblTitulo2Nombre.setBounds(30, 100, 120, 34);

        lblTituloTipoDocumento.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloTipoDocumento.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTituloTipoDocumento.setText("Tipo de Documento:");
        lblTituloTipoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloTipoDocumentoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloTipoDocumento);
        lblTituloTipoDocumento.setBounds(30, 160, 250, 34);

        lblTitulo2TipoSangre.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo2TipoSangre.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTitulo2TipoSangre.setText("Fecha de Nacimiento:");
        lblTitulo2TipoSangre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTitulo2TipoSangreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTitulo2TipoSangre);
        lblTitulo2TipoSangre.setBounds(470, 90, 280, 34);

        lblTituloEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloEmail.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTituloEmail.setText("Email:");
        lblTituloEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloEmailMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloEmail);
        lblTituloEmail.setBounds(30, 220, 90, 34);

        lblTituloCelular.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloCelular.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTituloCelular.setText("Celular:");
        lblTituloCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloCelularMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloCelular);
        lblTituloCelular.setBounds(30, 280, 110, 34);

        cbTipoDocumento.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "C.C", "C.E", "T.I", "P.N" }));
        FondoPrincipal.add(cbTipoDocumento);
        cbTipoDocumento.setBounds(280, 160, 130, 31);
        FondoPrincipal.add(txtEmail);
        txtEmail.setBounds(140, 220, 160, 22);
        FondoPrincipal.add(txtCelular);
        txtCelular.setBounds(140, 280, 160, 22);

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNombreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblNombre);
        lblNombre.setBounds(140, 90, 310, 34);

        lblFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblFechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFechaNacimientoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblFechaNacimiento);
        lblFechaNacimiento.setBounds(730, 80, 150, 40);

        lblTituloTipoDocumento1.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloTipoDocumento1.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTituloTipoDocumento1.setText("Ocupación:");
        lblTituloTipoDocumento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloTipoDocumento1MouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloTipoDocumento1);
        lblTituloTipoDocumento1.setBounds(470, 270, 140, 34);

        lblTituloTipoDocumento2.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloTipoDocumento2.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTituloTipoDocumento2.setText("Documento:");
        lblTituloTipoDocumento2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloTipoDocumento2MouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloTipoDocumento2);
        lblTituloTipoDocumento2.setBounds(470, 150, 150, 34);

        lblTituloTipoDocumento3.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloTipoDocumento3.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTituloTipoDocumento3.setText("Dirección:");
        lblTituloTipoDocumento3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloTipoDocumento3MouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloTipoDocumento3);
        lblTituloTipoDocumento3.setBounds(470, 210, 130, 34);
        FondoPrincipal.add(txtDocumento);
        txtDocumento.setBounds(630, 150, 160, 22);
        FondoPrincipal.add(txtDireccion);
        txtDireccion.setBounds(630, 210, 170, 22);
        FondoPrincipal.add(txtOcupacion);
        txtOcupacion.setBounds(630, 270, 170, 22);

        jButton1.setBackground(new java.awt.Color(173, 220, 255));
        jButton1.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        FondoPrincipal.add(jButton1);
        jButton1.setBounds(350, 340, 130, 34);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTituloCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloCelularMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloCelularMouseClicked

    private void lblTituloEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloEmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloEmailMouseClicked

    private void lblTitulo2TipoSangreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTitulo2TipoSangreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTitulo2TipoSangreMouseClicked

    private void lblTituloTipoDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloTipoDocumentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloTipoDocumentoMouseClicked

    private void lblTitulo2NombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTitulo2NombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTitulo2NombreMouseClicked

    private void lblTituloConfiguraciónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloConfiguraciónMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloConfiguraciónMouseClicked

    private void lblNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNombreMouseClicked

    private void lblFechaNacimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFechaNacimientoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFechaNacimientoMouseClicked

    private void lblTituloTipoDocumento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloTipoDocumento1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloTipoDocumento1MouseClicked

    private void lblTituloTipoDocumento2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloTipoDocumento2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloTipoDocumento2MouseClicked

    private void lblTituloTipoDocumento3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloTipoDocumento3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloTipoDocumento3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nuevoTipoDocumento = (String) cbTipoDocumento.getSelectedItem();
        String nuevoEmail = txtEmail.getText();
        String nuevoCelular = txtCelular.getText();
        String nuevoDocumento = txtDocumento.getText();
        String nuevoDireccion = txtDireccion.getText();
        String nuevoOcupacion = txtOcupacion.getText();
        
        

       // Crear un objeto Paciente con los nuevos valores
       Paciente paciente = new Paciente();
       paciente.setTipoDocumento(nuevoTipoDocumento);
       paciente.setEmail(nuevoEmail);
       paciente.setCelular(nuevoCelular);
       paciente.setDocumento(nuevoDocumento);
       paciente.setDireccion(nuevoDireccion);
       paciente.setOcupacion(nuevoOcupacion);  // Suponiendo que ya tienes el documento del paciente

       // Llamar al controlador para actualizar los datos en la base de datos
       ControladorAcciones controlador = new ControladorAcciones();
       boolean exito = controlador.actualizarPaciente(paciente);

       if (exito) {
        JOptionPane.showMessageDialog(this, "Datos actualizados correctamente.");
       } else {
        JOptionPane.showMessageDialog(this, "Error al actualizar los datos.");
       }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JComboBox<String> cbTipoDocumento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo2Nombre;
    private javax.swing.JLabel lblTitulo2TipoSangre;
    private javax.swing.JLabel lblTituloCelular;
    private javax.swing.JLabel lblTituloConfiguración;
    private javax.swing.JLabel lblTituloEmail;
    private javax.swing.JLabel lblTituloTipoDocumento;
    private javax.swing.JLabel lblTituloTipoDocumento1;
    private javax.swing.JLabel lblTituloTipoDocumento2;
    private javax.swing.JLabel lblTituloTipoDocumento3;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOcupacion;
    // End of variables declaration//GEN-END:variables
}
