    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAcciones;
import javax.swing.JDesktopPane;
import Controlador.PacienteDAO;
import Modelo.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class Menu_Admin_Pacientes extends javax.swing.JInternalFrame {
    private JDesktopPane escritorio; 
    private ControladorAcciones controlador;

    /**
     * Creates new form Menu_Doctor_Diagnosticos
     */
    public Menu_Admin_Pacientes(JDesktopPane escritorio) {
        initComponents();
        this.escritorio = escritorio;
        this.controlador = new ControladorAcciones();
        configurarTablaPacientes();
    }
    
     private void configurarTablaPacientes() {
        jTablePacientes.setModel(controlador.obtenerPacientesMenuAdmin());

        // Ajustar columnas
        jTablePacientes.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTablePacientes.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTablePacientes.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTablePacientes.getColumnModel().getColumn(3).setPreferredWidth(100);

        // Ajustar altura de filas
        jTablePacientes.setRowHeight(40);
        jTablePacientes.getColumnModel().getColumn(0).setMinWidth(0);
        jTablePacientes.getColumnModel().getColumn(0).setMaxWidth(0);
        jTablePacientes.getColumnModel().getColumn(0).setWidth(0);
 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblHistoriasClinicas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Medicos");
        setPreferredSize(new java.awt.Dimension(1099, 664));

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblHistoriasClinicas.setBackground(new java.awt.Color(255, 255, 255));
        lblHistoriasClinicas.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblHistoriasClinicas.setText("Lista Pacientes");
        lblHistoriasClinicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHistoriasClinicasMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblHistoriasClinicas);
        lblHistoriasClinicas.setBounds(70, 40, 300, 34);

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePacientes);

        FondoPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(70, 120, 960, 400);

        lblBuscar.setBackground(new java.awt.Color(255, 255, 255));
        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblBuscar.setText("Buscar :");
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblBuscar);
        lblBuscar.setBounds(680, 40, 100, 34);
        FondoPrincipal.add(txtBuscar);
        txtBuscar.setBounds(790, 30, 220, 50);

        btnRegistrar.setBackground(new java.awt.Color(173, 220, 255));
        btnRegistrar.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnRegistrar);
        btnRegistrar.setBounds(500, 540, 150, 45);

        btnModificar.setBackground(new java.awt.Color(173, 220, 255));
        btnModificar.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnModificar);
        btnModificar.setBounds(680, 540, 160, 45);

        btnEliminar.setBackground(new java.awt.Color(173, 220, 255));
        btnEliminar.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnEliminar);
        btnEliminar.setBounds(870, 540, 160, 45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHistoriasClinicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoriasClinicasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHistoriasClinicasMouseClicked

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        Menu_Admin_Pacientes_Registrar verventana = new Menu_Admin_Pacientes_Registrar();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    int selectedRow = jTablePacientes.getSelectedRow();

if (selectedRow != -1) {
    int pacienteId = Integer.parseInt(jTablePacientes.getValueAt(selectedRow, 0).toString());

    System.out.println("ID del paciente seleccionado: " + pacienteId);

    PacienteDAO dao = new PacienteDAO();
    Paciente paciente = dao.obtenerPacientePorId(pacienteId);

    if (paciente != null) {
        Menu_Admin_Pacientes_Modificar ventanaModificar = new Menu_Admin_Pacientes_Modificar(paciente);
        escritorio.add(ventanaModificar);
        ventanaModificar.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró al paciente.");
    }
} else {
    JOptionPane.showMessageDialog(this, "Por favor, selecciona un paciente de la tabla.");
}

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblHistoriasClinicas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
