/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAcciones;
import Controlador.PacienteDAO;
import Modelo.CitaMedica;
import Modelo.Paciente;
import Modelo.Sesion;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;



/**
 *
 * @author marti
 */
public class Menu_Paciente_Agendar_Cita_Medica extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu_Doctor_TotalPacientes
     */
    public Menu_Paciente_Agendar_Cita_Medica() {
        initComponents();
        ControladorAcciones.cargarMedicosEnComboBox(cbMedicos);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblVerCitaAgendada = new javax.swing.JLabel();
        lblTituloFecha = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTituloHora = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblTituloMedico = new javax.swing.JLabel();
        lblTituloEspecialidad = new javax.swing.JLabel();
        cbMedicos = new javax.swing.JComboBox<>();
        cbEspecialidad = new javax.swing.JComboBox<>();
        btnAgendar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Agendar Cita");
        setPreferredSize(new java.awt.Dimension(841, 496));

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblVerCitaAgendada.setBackground(new java.awt.Color(255, 255, 255));
        lblVerCitaAgendada.setFont(new java.awt.Font("Sylfaen", 1, 38)); // NOI18N
        lblVerCitaAgendada.setText("Agendar Cita Medica");
        lblVerCitaAgendada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerCitaAgendadaMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblVerCitaAgendada);
        lblVerCitaAgendada.setBounds(250, 20, 380, 50);

        lblTituloFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloFecha.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloFecha.setText("Fecha");
        lblTituloFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloFechaMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloFecha);
        lblTituloFecha.setBounds(160, 120, 80, 34);

        lblFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblFecha.setText("xx/xx/xxxx");
        lblFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFechaMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblFecha);
        lblFecha.setBounds(130, 160, 150, 34);

        lblTituloHora.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloHora.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloHora.setText("Hora");
        lblTituloHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloHoraMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloHora);
        lblTituloHora.setBounds(610, 110, 70, 34);

        lblHora.setBackground(new java.awt.Color(255, 255, 255));
        lblHora.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblHora.setText("XX:XX");
        lblHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoraMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblHora);
        lblHora.setBounds(610, 150, 80, 34);

        lblTituloMedico.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloMedico.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloMedico.setText("Médico");
        lblTituloMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloMedicoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloMedico);
        lblTituloMedico.setBounds(150, 280, 100, 34);

        lblTituloEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloEspecialidad.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        lblTituloEspecialidad.setText("Especialidad");
        lblTituloEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloEspecialidadMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloEspecialidad);
        lblTituloEspecialidad.setBounds(580, 280, 170, 34);

        cbMedicos.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cbMedicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cbMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedicosActionPerformed(evt);
            }
        });
        FondoPrincipal.add(cbMedicos);
        cbMedicos.setBounds(110, 330, 180, 31);

        cbEspecialidad.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Medicina General", "Cardiología", "Neurología", "Ginecología", "Obstetricia", "Pediatría", "Oftalmología", "Odontología" }));
        cbEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspecialidadActionPerformed(evt);
            }
        });
        FondoPrincipal.add(cbEspecialidad);
        cbEspecialidad.setBounds(570, 330, 190, 30);

        btnAgendar.setBackground(new java.awt.Color(173, 220, 255));
        btnAgendar.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        btnAgendar.setText("Agendar Cita");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnAgendar);
        btnAgendar.setBounds(350, 400, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVerCitaAgendadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerCitaAgendadaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVerCitaAgendadaMouseClicked

    private void lblTituloFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloFechaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloFechaMouseClicked

    private void lblFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFechaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFechaMouseClicked

    private void lblTituloHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloHoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloHoraMouseClicked

    private void lblHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHoraMouseClicked

    private void lblTituloMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMedicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloMedicoMouseClicked

    private void lblTituloEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloEspecialidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloEspecialidadMouseClicked

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // TODO add your handling code here:
        String especialidad = cbEspecialidad.getSelectedItem().toString();
        String medico = cbMedicos.getSelectedItem().toString();
        String documentoPaciente = Sesion.getPaciente().getDocumento(); // Asumiendo que guardaste el paciente al iniciar sesión

    CitaMedica cita = new CitaMedica.Builder()
            .setEspecialidad(especialidad)
            .setMedico(medico)
            .setDocumentoPaciente(documentoPaciente)
            .build();

    ControladorAcciones controlador = new ControladorAcciones();
    if (controlador.agendarCita(cita)) {
        JOptionPane.showMessageDialog(this, "Cita agendada correctamente. El médico asignará fecha y hora.");
    } else {
        JOptionPane.showMessageDialog(this, "Error al agendar cita.");
    }
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void cbMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMedicosActionPerformed

    private void cbEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEspecialidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JButton btnAgendar;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JComboBox<String> cbMedicos;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblTituloEspecialidad;
    private javax.swing.JLabel lblTituloFecha;
    private javax.swing.JLabel lblTituloHora;
    private javax.swing.JLabel lblTituloMedico;
    private javax.swing.JLabel lblVerCitaAgendada;
    // End of variables declaration//GEN-END:variables
}
