/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.sql.Connection;
import Controlador.ConexionBD;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class MenuPrincipal extends javax.swing.JFrame {

    Connection con = ConexionBD.getInstancia().getConexion();
    
    
    
    

    
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        


    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblAboutUs = new javax.swing.JLabel();
        imgDoctoa = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        imgDecoracion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setPreferredSize(new java.awt.Dimension(1327, 705));
        FondoPrincipal.setLayout(null);

        lblLogin.setBackground(new java.awt.Color(255, 255, 255));
        lblLogin.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblLogin.setText("LOGIN");
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblLogin);
        lblLogin.setBounds(1150, 40, 140, 48);

        lblTitulo2.setFont(new java.awt.Font("Palatino Linotype", 1, 52)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(0, 0, 153));
        lblTitulo2.setText("nuestra prioridad");
        FondoPrincipal.add(lblTitulo2);
        lblTitulo2.setBounds(20, 290, 440, 80);

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Logos/LogoSinFondo.png"))); // NOI18N
        FondoPrincipal.add(imgLogo);
        imgLogo.setBounds(0, 0, 350, 111);

        lblContact.setBackground(new java.awt.Color(255, 255, 255));
        lblContact.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblContact.setText("CONTACT");
        lblContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContactMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblContact);
        lblContact.setBounds(860, 40, 190, 48);

        lblHome.setBackground(new java.awt.Color(255, 255, 255));
        lblHome.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblHome.setText("HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblHome);
        lblHome.setBounds(380, 40, 130, 48);

        lblAboutUs.setBackground(new java.awt.Color(255, 255, 255));
        lblAboutUs.setFont(new java.awt.Font("Palatino Linotype", 1, 35)); // NOI18N
        lblAboutUs.setText("ABOUT US");
        lblAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutUsMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblAboutUs);
        lblAboutUs.setBounds(580, 40, 200, 48);

        imgDoctoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Personas/Doctora.png"))); // NOI18N
        FondoPrincipal.add(imgDoctoa);
        imgDoctoa.setBounds(340, 50, 790, 600);

        lblTitulo1.setFont(new java.awt.Font("Palatino Linotype", 1, 52)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(0, 0, 153));
        lblTitulo1.setText("Tu salud,");
        FondoPrincipal.add(lblTitulo1);
        lblTitulo1.setBounds(20, 240, 240, 70);

        lblDescripcion.setFont(new java.awt.Font("Arial Narrow", 0, 28)); // NOI18N
        lblDescripcion.setText("<html>Gestiona tus consultas médicas de <p>forma rápida y sin complicaciones. <p>Tu salud, más accesible que nunca.</html>");
        FondoPrincipal.add(lblDescripcion);
        lblDescripcion.setBounds(20, 320, 370, 170);

        imgDecoracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Decoraciones/DecoracionMenu.jpg"))); // NOI18N
        imgDecoracion.setText("jLabel2");
        FondoPrincipal.add(imgDecoracion);
        imgDecoracion.setBounds(1000, -120, 330, 460);
        imgDecoracion.getAccessibleContext().setAccessibleName("lblDecoracion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        // TODO add your handling code here:
        IniciarSesion form=new IniciarSesion();
        form.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContactMouseClicked
        // TODO add your handling code here:
        Contact form=new Contact();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblContactMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ya estas en el menu principal");
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutUsMouseClicked
        // TODO add your handling code here:
         AboutUs form=new AboutUs();
         form.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_lblAboutUsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JLabel imgDecoracion;
    private javax.swing.JLabel imgDoctoa;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblAboutUs;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    // End of variables declaration//GEN-END:variables
}
