/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAcciones;
import javax.swing.table.TableColumn;
import javax.swing.JDesktopPane;



/**
 *
 * @author marti
 */
public class Menu_Paciente_Plan_de_Tratamiento extends javax.swing.JInternalFrame {
   

    /**
     * Creates new form Menu_Doctor_TotalPacientes
     */
    public Menu_Paciente_Plan_de_Tratamiento(JDesktopPane escritorio) {
        initComponents();
       
  
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblListaDePacientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedicamentos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Pacientes");
        setPreferredSize(new java.awt.Dimension(1099, 664));

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblListaDePacientes.setBackground(new java.awt.Color(255, 255, 255));
        lblListaDePacientes.setFont(new java.awt.Font("Sylfaen", 1, 40)); // NOI18N
        lblListaDePacientes.setText("Medicamentos Actuales");
        lblListaDePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListaDePacientesMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblListaDePacientes);
        lblListaDePacientes.setBounds(70, 30, 470, 54);

        jTableMedicamentos.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jTableMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMedicamentos);

        FondoPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(70, 90, 940, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblListaDePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDePacientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblListaDePacientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedicamentos;
    private javax.swing.JLabel lblListaDePacientes;
    // End of variables declaration//GEN-END:variables
}
