/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.DoctorDAO;
import Modelo.Medico;
import javax.swing.JOptionPane;




/**
 *
 * @author marti
 */
public class Menu_Admin_Medicos_Modificar extends javax.swing.JInternalFrame {
    private Medico medico;
    

    /**
     * Creates new form Menu_Doctor_TotalPacientes
     */
    public Menu_Admin_Medicos_Modificar(Medico medico) {
        initComponents();
        this.medico = medico;
     
        lblNombre.setText(medico.getNombres() + " " + medico.getApellidos());

        if (medico.getFechaNacimiento() != null) {
            lblFechaNacimiento.setText(medico.getFechaNacimiento().toString());
        } else {
            lblFechaNacimiento.setText("Fecha no disponible");
        }

        txtEmail.setText(medico.getEmail());
        txtCelular.setText(medico.getCelular());
        txtDireccion.setText(medico.getDireccion());
        cbEspecialidad.setSelectedItem(medico.getEspecialidad());
        txtContrasena.setText(medico.getContrasena());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblTituloConfiguración = new javax.swing.JLabel();
        lblTitulo2Nombre = new javax.swing.JLabel();
        lblTitulo2TipoSangre = new javax.swing.JLabel();
        lblTituloEmail = new javax.swing.JLabel();
        lblTituloCelular = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblTituloTipoDocumento3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        cbEspecialidad = new javax.swing.JComboBox<>();
        txtContrasena = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Modificar Medico");
        setPreferredSize(new java.awt.Dimension(908, 462));

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblTituloConfiguración.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloConfiguración.setFont(new java.awt.Font("Sylfaen", 1, 38)); // NOI18N
        lblTituloConfiguración.setText("Modificar Médico");
        lblTituloConfiguración.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloConfiguraciónMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloConfiguración);
        lblTituloConfiguración.setBounds(280, 10, 310, 50);

        lblTitulo2Nombre.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo2Nombre.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTitulo2Nombre.setText("Nombre:");
        lblTitulo2Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTitulo2NombreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTitulo2Nombre);
        lblTitulo2Nombre.setBounds(30, 100, 120, 34);

        lblTitulo2TipoSangre.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo2TipoSangre.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTitulo2TipoSangre.setText("Fecha de Nacimiento:");
        lblTitulo2TipoSangre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTitulo2TipoSangreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTitulo2TipoSangre);
        lblTitulo2TipoSangre.setBounds(470, 90, 280, 34);

        lblTituloEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloEmail.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTituloEmail.setText("Email:");
        lblTituloEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloEmailMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloEmail);
        lblTituloEmail.setBounds(30, 200, 90, 34);

        lblTituloCelular.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloCelular.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTituloCelular.setText("Celular:");
        lblTituloCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloCelularMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloCelular);
        lblTituloCelular.setBounds(30, 260, 110, 34);

        txtEmail.setBackground(new java.awt.Color(220, 233, 255));
        txtEmail.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        FondoPrincipal.add(txtEmail);
        txtEmail.setBounds(140, 192, 260, 30);

        txtCelular.setBackground(new java.awt.Color(220, 233, 255));
        txtCelular.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        FondoPrincipal.add(txtCelular);
        txtCelular.setBounds(140, 252, 270, 30);

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNombreMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblNombre);
        lblNombre.setBounds(140, 90, 310, 34);

        lblFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblFechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFechaNacimientoMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblFechaNacimiento);
        lblFechaNacimiento.setBounds(730, 80, 150, 40);

        lblTituloTipoDocumento3.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloTipoDocumento3.setFont(new java.awt.Font("Sylfaen", 1, 26)); // NOI18N
        lblTituloTipoDocumento3.setText("Dirección:");
        lblTituloTipoDocumento3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloTipoDocumento3MouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblTituloTipoDocumento3);
        lblTituloTipoDocumento3.setBounds(30, 150, 130, 36);

        txtDireccion.setBackground(new java.awt.Color(220, 233, 255));
        txtDireccion.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        FondoPrincipal.add(txtDireccion);
        txtDireccion.setBounds(160, 140, 260, 30);

        btnActualizar.setBackground(new java.awt.Color(173, 220, 255));
        btnActualizar.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbtnActualizarActionPerformed(evt);
            }
        });
        FondoPrincipal.add(btnActualizar);
        btnActualizar.setBounds(350, 340, 130, 34);

        cbEspecialidad.setBackground(new java.awt.Color(220, 233, 255));
        cbEspecialidad.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        cbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especialidad", "Medicina General", "Cardiología", "Neurología", "Ginecología", "Obstetricia", "Pediatría", "Oftalmología", "Odontología" }));
        cbEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspecialidadActionPerformed(evt);
            }
        });
        FondoPrincipal.add(cbEspecialidad);
        cbEspecialidad.setBounds(470, 140, 230, 40);

        txtContrasena.setBackground(new java.awt.Color(220, 233, 255));
        txtContrasena.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtContrasena.setText("Contraseña");
        FondoPrincipal.add(txtContrasena);
        txtContrasena.setBounds(470, 200, 290, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTituloCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloCelularMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloCelularMouseClicked

    private void lblTituloEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloEmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloEmailMouseClicked

    private void lblTitulo2TipoSangreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTitulo2TipoSangreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTitulo2TipoSangreMouseClicked

    private void lblTitulo2NombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTitulo2NombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTitulo2NombreMouseClicked

    private void lblTituloConfiguraciónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloConfiguraciónMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloConfiguraciónMouseClicked

    private void lblNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNombreMouseClicked

    private void lblFechaNacimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFechaNacimientoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFechaNacimientoMouseClicked

    private void lblTituloTipoDocumento3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloTipoDocumento3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloTipoDocumento3MouseClicked

    private void btnbtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbtnActualizarActionPerformed
        medico.setDireccion(txtDireccion.getText());
        medico.setEspecialidad((String) cbEspecialidad.getSelectedItem());
        medico.setEmail(txtEmail.getText());
        medico.setContrasena(txtContrasena.getText());
        medico.setCelular(txtCelular.getText());

        DoctorDAO medicoDAO = new DoctorDAO();
        boolean actualizado = medicoDAO.actualizarDatosMedico(medico);

        if (actualizado) {
            JOptionPane.showMessageDialog(this, "Datos actualizados correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar los datos.");
        }
    }//GEN-LAST:event_btnbtnActualizarActionPerformed

    private void cbEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEspecialidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo2Nombre;
    private javax.swing.JLabel lblTitulo2TipoSangre;
    private javax.swing.JLabel lblTituloCelular;
    private javax.swing.JLabel lblTituloConfiguración;
    private javax.swing.JLabel lblTituloEmail;
    private javax.swing.JLabel lblTituloTipoDocumento3;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
