/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorAcciones;
import javax.swing.table.TableColumn;
import javax.swing.JDesktopPane;



/**
 *
 * @author marti
 */
public class Menu_Doctor_TotalPacientes extends javax.swing.JInternalFrame {
    private JDesktopPane escritorio;
    private ControladorAcciones controlador;

    /**
     * Creates new form Menu_Doctor_TotalPacientes
     */
    public Menu_Doctor_TotalPacientes(JDesktopPane escritorio) {
        initComponents();
        this.escritorio = escritorio;
        this.controlador = new ControladorAcciones();
        configurarTablaPacientes();
        
    }
    
    private void configurarTablaPacientes() {
        jTablePacientes.setModel(controlador.obtenerPacientes());

        // Ajustar columnas
        jTablePacientes.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTablePacientes.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTablePacientes.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTablePacientes.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTablePacientes.getColumnModel().getColumn(4).setPreferredWidth(120);

        // Ajustar altura de filas
        jTablePacientes.setRowHeight(40);

        // Renderizador y editor de botones
        TableColumn columnaOpciones = jTablePacientes.getColumnModel().getColumn(4);
        columnaOpciones.setCellRenderer(new RenderizadorBoton());
        columnaOpciones.setCellEditor(new EditorBoton(escritorio , jTablePacientes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblListaDePacientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Pacientes");
        setPreferredSize(new java.awt.Dimension(1099, 664));

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblListaDePacientes.setBackground(new java.awt.Color(255, 255, 255));
        lblListaDePacientes.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblListaDePacientes.setText("Lista de Pacientes");
        lblListaDePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListaDePacientesMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblListaDePacientes);
        lblListaDePacientes.setBounds(70, 40, 230, 34);

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePacientes);

        FondoPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(70, 120, 940, 410);
        FondoPrincipal.add(txtBuscar);
        txtBuscar.setBounds(790, 30, 220, 50);

        lblBuscar.setBackground(new java.awt.Color(255, 255, 255));
        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblBuscar.setText("Buscar :");
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblBuscar);
        lblBuscar.setBounds(680, 40, 100, 34);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblListaDePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListaDePacientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblListaDePacientesMouseClicked

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblListaDePacientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
