/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author marti
 */
public class Mision_Vision extends javax.swing.JFrame {

    /**
     * Creates new form Mision_Vision
     */
    public Mision_Vision() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMision = new javax.swing.JLabel();
        lblDescripcionMision = new javax.swing.JLabel();
        lblDescripcionVision = new javax.swing.JLabel();
        lblVision = new javax.swing.JLabel();
        imgFondoCuadro = new javax.swing.JLabel();
        imgFondoCuadro2 = new javax.swing.JLabel();
        lblDescripcion1 = new javax.swing.JLabel();
        lblDescripcion2 = new javax.swing.JLabel();
        lblDescripcion3 = new javax.swing.JLabel();
        lblDescripcion4 = new javax.swing.JLabel();
        imgVerificacion1 = new javax.swing.JLabel();
        imgVerificacion2 = new javax.swing.JLabel();
        imgTablaDecoracion = new javax.swing.JLabel();
        imgVerificacion3 = new javax.swing.JLabel();
        imgVerificacion4 = new javax.swing.JLabel();
        imgDecoracion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Sylfaen", 1, 38)); // NOI18N
        lblTitulo.setText("Nuestros Valores");
        FondoPrincipal.add(lblTitulo);
        lblTitulo.setBounds(740, 360, 310, 50);

        lblMision.setFont(new java.awt.Font("Palatino Linotype", 1, 38)); // NOI18N
        lblMision.setText("<html><center>Misión</html>");
        FondoPrincipal.add(lblMision);
        lblMision.setBounds(300, 30, 130, 50);

        lblDescripcionMision.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lblDescripcionMision.setText("<html><p align=\"justify\">Facilitar la gestión de citas <p>médicas con tecnología intuitiva,<p>conectando pacientes y <p>profesionales de salud de manera <p>rápida, eficiente y segura.</p></html>");
        FondoPrincipal.add(lblDescripcionMision);
        lblDescripcionMision.setBounds(220, 70, 310, 200);

        lblDescripcionVision.setFont(new java.awt.Font("Arial Narrow", 0, 25)); // NOI18N
        lblDescripcionVision.setText("<html><p align=\"justify\">Ser la plataforma líder en <p> agendamiento médico,<p>transformando la experiencia de <p>atención en salud con innovación <p>y accesibilidad para todos.</p></html> ");
        FondoPrincipal.add(lblDescripcionVision);
        lblDescripcionVision.setBounds(740, 80, 320, 170);

        lblVision.setFont(new java.awt.Font("Palatino Linotype", 1, 38)); // NOI18N
        lblVision.setText("<html><center>Visión</html>");
        FondoPrincipal.add(lblVision);
        lblVision.setBounds(840, 30, 130, 50);

        imgFondoCuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/FondoCuadro.png"))); // NOI18N
        FondoPrincipal.add(imgFondoCuadro);
        imgFondoCuadro.setBounds(210, 60, 320, 220);

        imgFondoCuadro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/FondoCuadro.png"))); // NOI18N
        FondoPrincipal.add(imgFondoCuadro2);
        imgFondoCuadro2.setBounds(730, 60, 320, 220);

        lblDescripcion1.setFont(new java.awt.Font("Arial Narrow", 0, 28)); // NOI18N
        lblDescripcion1.setText("Compromiso con la salud.\n");
        FondoPrincipal.add(lblDescripcion1);
        lblDescripcion1.setBounds(780, 420, 290, 30);

        lblDescripcion2.setFont(new java.awt.Font("Arial Narrow", 0, 28)); // NOI18N
        lblDescripcion2.setText("Innovación y tecnología.");
        FondoPrincipal.add(lblDescripcion2);
        lblDescripcion2.setBounds(780, 470, 260, 40);

        lblDescripcion3.setFont(new java.awt.Font("Arial Narrow", 0, 28)); // NOI18N
        lblDescripcion3.setText("Accesibilidad para todos.");
        FondoPrincipal.add(lblDescripcion3);
        lblDescripcion3.setBounds(780, 530, 260, 40);

        lblDescripcion4.setFont(new java.awt.Font("Arial Narrow", 0, 28)); // NOI18N
        lblDescripcion4.setText("Seguridad y confianza.");
        FondoPrincipal.add(lblDescripcion4);
        lblDescripcion4.setBounds(780, 590, 260, 50);

        imgVerificacion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/Verificacion.jpg"))); // NOI18N
        imgVerificacion1.setText("jLabel2");
        FondoPrincipal.add(imgVerificacion1);
        imgVerificacion1.setBounds(730, 410, 50, 50);

        imgVerificacion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/Verificacion.jpg"))); // NOI18N
        imgVerificacion2.setText("jLabel2");
        FondoPrincipal.add(imgVerificacion2);
        imgVerificacion2.setBounds(730, 470, 50, 50);

        imgTablaDecoracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/TablaRevision.jpg"))); // NOI18N
        FondoPrincipal.add(imgTablaDecoracion);
        imgTablaDecoracion.setBounds(270, 450, 180, 220);

        imgVerificacion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/Verificacion.jpg"))); // NOI18N
        imgVerificacion3.setText("jLabel2");
        FondoPrincipal.add(imgVerificacion3);
        imgVerificacion3.setBounds(730, 530, 50, 50);

        imgVerificacion4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Objetos/Verificacion.jpg"))); // NOI18N
        imgVerificacion4.setText("jLabel2");
        FondoPrincipal.add(imgVerificacion4);
        imgVerificacion4.setBounds(730, 590, 50, 50);

        imgDecoracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Decoraciones/DecoracionMenu3.png"))); // NOI18N
        FondoPrincipal.add(imgDecoracion);
        imgDecoracion.setBounds(-400, 290, 1190, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mision_Vision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mision_Vision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mision_Vision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mision_Vision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mision_Vision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPrincipal;
    private javax.swing.JLabel imgDecoracion;
    private javax.swing.JLabel imgFondoCuadro;
    private javax.swing.JLabel imgFondoCuadro2;
    private javax.swing.JLabel imgTablaDecoracion;
    private javax.swing.JLabel imgVerificacion1;
    private javax.swing.JLabel imgVerificacion2;
    private javax.swing.JLabel imgVerificacion3;
    private javax.swing.JLabel imgVerificacion4;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblDescripcion2;
    private javax.swing.JLabel lblDescripcion3;
    private javax.swing.JLabel lblDescripcion4;
    private javax.swing.JLabel lblDescripcionMision;
    private javax.swing.JLabel lblDescripcionVision;
    private javax.swing.JLabel lblMision;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVision;
    // End of variables declaration//GEN-END:variables
}
