/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Paciente;
import Controlador.PacienteDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author marti
 */
public class Registro extends javax.swing.JFrame {
    
    
    public Registro() {
    initComponents();
    setLocationRelativeTo(null); // Centra la ventana
    setResizable(false); // Evita que el usuario cambie el tamaño
    }


    /**
     * Creates new form IniciarSesion
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPrincipal = new javax.swing.JPanel();
        FondoColor = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        lbIVolver = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();
        lblInicioSesion = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        cbTipoDocumento = new javax.swing.JComboBox<>();
        txtDocumento = new javax.swing.JTextField();
        calendarFecha = new com.toedter.calendar.JDateChooser();
        cbGenero = new javax.swing.JComboBox<>();
        cbTipoSangre = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAlergias = new javax.swing.JTextArea();
        cbEnfermedadesCronicas = new javax.swing.JComboBox<>();
        txtCelular = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtOcupacion = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEPS = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        FondoPrincipal.setLayout(null);

        FondoColor.setBackground(new java.awt.Color(220, 233, 255));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Logos/Logo_Descripcion.png"))); // NOI18N

        lbIVolver.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        lbIVolver.setText("Volver");
        lbIVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FondoColorLayout = new javax.swing.GroupLayout(FondoColor);
        FondoColor.setLayout(FondoColorLayout);
        FondoColorLayout.setHorizontalGroup(
            FondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoColorLayout.createSequentialGroup()
                .addGroup(FondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoColorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbIVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoColorLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        FondoColorLayout.setVerticalGroup(
            FondoColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoColorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbIVolver)
                .addGap(221, 221, 221)
                .addComponent(imgLogo)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        FondoPrincipal.add(FondoColor);
        FondoColor.setBounds(0, 0, 546, 800);

        lblRegistro.setFont(new java.awt.Font("Sylfaen", 1, 35)); // NOI18N
        lblRegistro.setText("Registro");
        lblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistroMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblRegistro);
        lblRegistro.setBounds(1150, 40, 157, 41);

        lblInicioSesion.setFont(new java.awt.Font("Sylfaen", 1, 35)); // NOI18N
        lblInicioSesion.setText("Inicio Sesión");
        lblInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInicioSesionMouseClicked(evt);
            }
        });
        FondoPrincipal.add(lblInicioSesion);
        lblInicioSesion.setBounds(640, 30, 230, 64);

        txtNombres.setBackground(new java.awt.Color(220, 233, 255));
        txtNombres.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtNombres.setText("Nombres");
        FondoPrincipal.add(txtNombres);
        txtNombres.setBounds(580, 100, 345, 40);

        txtApellidos.setBackground(new java.awt.Color(220, 233, 255));
        txtApellidos.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtApellidos.setText("Apellidos");
        FondoPrincipal.add(txtApellidos);
        txtApellidos.setBounds(580, 150, 345, 40);

        cbTipoDocumento.setBackground(new java.awt.Color(220, 233, 255));
        cbTipoDocumento.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        cbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "C.C", "C.E", "T.I", "P.A" }));
        FondoPrincipal.add(cbTipoDocumento);
        cbTipoDocumento.setBounds(580, 200, 130, 40);

        txtDocumento.setBackground(new java.awt.Color(220, 233, 255));
        txtDocumento.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtDocumento.setText("No. Documento");
        FondoPrincipal.add(txtDocumento);
        txtDocumento.setBounds(730, 200, 345, 40);
        FondoPrincipal.add(calendarFecha);
        calendarFecha.setBounds(1120, 200, 130, 40);

        cbGenero.setBackground(new java.awt.Color(220, 233, 255));
        cbGenero.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genero", "Masculino", "Femenino" }));
        FondoPrincipal.add(cbGenero);
        cbGenero.setBounds(580, 260, 130, 40);

        cbTipoSangre.setBackground(new java.awt.Color(220, 233, 255));
        cbTipoSangre.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        cbTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo De Sangre", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        FondoPrincipal.add(cbTipoSangre);
        cbTipoSangre.setBounds(730, 260, 190, 40);

        txtAreaAlergias.setBackground(new java.awt.Color(220, 233, 255));
        txtAreaAlergias.setColumns(20);
        txtAreaAlergias.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtAreaAlergias.setRows(5);
        txtAreaAlergias.setText("Alergias");
        jScrollPane1.setViewportView(txtAreaAlergias);

        FondoPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(580, 320, 260, 100);

        cbEnfermedadesCronicas.setBackground(new java.awt.Color(220, 233, 255));
        cbEnfermedadesCronicas.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        cbEnfermedadesCronicas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enfermedades Crónicas", "Cáncer", "Diabetes", "Hipertensión arterial", "Osteoartrsis", "Asma", "Artritis", "Cardiopatía", "Enfermedad Pulmonar", "Ninguna", "Otra" }));
        FondoPrincipal.add(cbEnfermedadesCronicas);
        cbEnfermedadesCronicas.setBounds(880, 320, 260, 40);

        txtCelular.setBackground(new java.awt.Color(220, 233, 255));
        txtCelular.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtCelular.setText("Celular");
        FondoPrincipal.add(txtCelular);
        txtCelular.setBounds(580, 450, 190, 40);

        txtEmail.setBackground(new java.awt.Color(220, 233, 255));
        txtEmail.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtEmail.setText("Email");
        FondoPrincipal.add(txtEmail);
        txtEmail.setBounds(860, 450, 290, 40);

        txtOcupacion.setBackground(new java.awt.Color(220, 233, 255));
        txtOcupacion.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtOcupacion.setText("Ocupación");
        FondoPrincipal.add(txtOcupacion);
        txtOcupacion.setBounds(580, 510, 190, 40);

        txtDireccion.setBackground(new java.awt.Color(220, 233, 255));
        txtDireccion.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtDireccion.setText("Dirección");
        FondoPrincipal.add(txtDireccion);
        txtDireccion.setBounds(860, 510, 290, 40);

        txtEPS.setBackground(new java.awt.Color(220, 233, 255));
        txtEPS.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtEPS.setText("EPS");
        FondoPrincipal.add(txtEPS);
        txtEPS.setBounds(580, 570, 190, 40);

        txtContrasena.setBackground(new java.awt.Color(220, 233, 255));
        txtContrasena.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtContrasena.setText("Contraseña");
        FondoPrincipal.add(txtContrasena);
        txtContrasena.setBounds(860, 570, 290, 40);

        jButton1.setBackground(new java.awt.Color(173, 220, 255));
        jButton1.setFont(new java.awt.Font("Sylfaen", 1, 28)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        FondoPrincipal.add(jButton1);
        jButton1.setBounds(580, 640, 180, 45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbIVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIVolverMouseClicked
        // TODO add your handling code here:
        IniciarSesion form = new IniciarSesion();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbIVolverMouseClicked

    private void lblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ya te estas registrando");
    }//GEN-LAST:event_lblRegistroMouseClicked

    private void lblInicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioSesionMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblInicioSesionMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          String fechaNacimiento = sdf.format(calendarFecha.getDate());

          Paciente nuevo = new Paciente(
          txtNombres.getText(),
          txtApellidos.getText(),
          cbTipoDocumento.getSelectedItem().toString(),
          txtDocumento.getText(),
          fechaNacimiento,
          cbGenero.getSelectedItem().toString(),
          cbTipoSangre.getSelectedItem().toString(),
          txtAreaAlergias.getText(),
          cbEnfermedadesCronicas.getSelectedItem().toString(),
          txtCelular.getText(),
          txtEmail.getText(),
          txtOcupacion.getText(),
          txtDireccion.getText(),
          txtEPS.getText(),
         txtContrasena.getText()

    );

        PacienteDAO dao = new PacienteDAO();
           if (dao.registrarPaciente(nuevo)) {
             JOptionPane.showMessageDialog(this, "Registro exitoso");
             IniciarSesion login = new IniciarSesion();
             login.setVisible(true);
             login.setLocationRelativeTo(null);
              this.dispose();     
            } else {
             JOptionPane.showMessageDialog(this, "Error al registrar");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoColor;
    private javax.swing.JPanel FondoPrincipal;
    private com.toedter.calendar.JDateChooser calendarFecha;
    private javax.swing.JComboBox<String> cbEnfermedadesCronicas;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JComboBox<String> cbTipoDocumento;
    private javax.swing.JComboBox<String> cbTipoSangre;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIVolver;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextArea txtAreaAlergias;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEPS;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtOcupacion;
    // End of variables declaration//GEN-END:variables
}
